<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>
<body>
<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-card-body">
            <div style="padding-bottom: 10px;">
                <a class="layui-btn" href="/active_vip/add">添加</a>
            </div>
            <table class="layui-table layui-form">
                <colgroup>
                    <col width="80">
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col width="80">
                </colgroup>
                <thead>
                <tr>
                    <th>编号</th>
                    <th>等级标记</th>
                    <th>等级名称</th>
                    <th>勋章图标</th>
                    <th>展示图标</th>
                    <th>所需经验</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($list as $item){?>
                    <tr data-id="<?=$item['id']?>">
                        <td><?=$item['id']?></td>
                        <td><?=$item['name']?></td>
                        <td><?=$item['alias']?></td>
                        <td><img height="28px" src="<?=$item['badge']?>" /></td>
                        <td><img height="28px" src="<?=$item['icon']?>" /></td>
                        <td><input type="text" name="exp" class="table-text exp" data-val="<?=$item['exp'];?>" value="<?=$item['exp'];?>"></td>
                        <td>
                            <a class="layui-btn layui-btn-xs" href="/active_vip/edit?id=<?=$item['id']?>&p=<?= $curpage ?>"><i class="layui-icon layui-icon-edit"></i>编辑</a>
                        </td>
                    </tr>
                <?php }?>
                </tbody>
            </table>
            <?= $page ?>
        </div>
    </div>
</div>

<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.use('form', function () {
        var $ = layui.$
            , form = layui.form;

        //修改所需经验值
        $('.exp').on('blur', function () {
            var id = $(this).closest('tr').data('id');
            var oldval = parseInt($(this).data('val'));
            var exp = parseInt($(this).val());
            var self = $(this);
            if (exp >= 0 && oldval != exp) {
                $.ajax({
                    type: "POST",
                    dataType: "JSON",
                    url: '/active_vip/update_exp',
                    data: {"id": id, "exp": exp},
                    success: function (json) {
                        if (json.code == 200) {
                            self.data('val', exp);
                            layer.msg('操作成功', {time: 800});
                        } else {
                            layer.alert(json.msg)
                        }
                    }
                })
            }
        });


    });
</script>
</body>
</html>
