<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>
<body>
<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-form layui-card-header layuiadmin-card-header-auto">
            <div class="layui-form-item">
                <form method="get">
                    <div style="float: right">
                        <div class="layui-inline">
                            <input type="text" name="id" value="<?= $id > 0 ? $id : ''; ?>" class="layui-input" placeholder="会员ID" style="width: 120px;" autocomplete="off">
                        </div>
                        <div class="layui-inline" style="width: 200px;">
                            <select name="type" id="">
                                <option value="">请选择日志类型</option>
                                <option value="1" <?= $type == 1 ? 'selected' : '' ?>>禁言</option>
                                <option value="2" <?= $type == 2 ? 'selected' : '' ?>>锁定用户</option>
                                <option value="3" <?= $type == 3 ? 'selected' : '' ?>>解锁用户</option>
                                <option value="4" <?= $type == 4 ? 'selected' : '' ?>>冻结余额</option>
                                <option value="5" <?= $type == 5 ? 'selected' : '' ?>>解锁余额</option>
                            </select>
                        </div>
                        <div class="layui-inline" style="width: 200px;">
                            <select name="admin_id" id="">
                                <option value="">请选择管理员</option>
                                <?php foreach ($adminList as $item) { ?>
                                    <option value="<?=$item['id']?>" <?= $admin_id == $item['id'] ? 'selected' : '' ?>><?=$item['nickname']?></option>
                                <?php } ?>
                            </select>
                        </div>
                        <div class="layui-inline" style="width: 120px;">
                            <input type="text" name="addtime" id="addtime" value="<?= $addtime ?>"
                                   placeholder="开始日期" autocomplete="off" class="layui-input">
                        </div>

                        <div class="layui-inline" style="width: 120px;">
                            <input type="text" name="endtime" id="endtime" value="<?= $endtime ?>"
                                   placeholder="结束日期" autocomplete="off" class="layui-input">
                        </div>
                        <div class="layui-inline" style="height: 44px">
                            <button class="layui-btn layuiadmin-btn-list" type="submit">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="layui-card-body">
            <table class="layui-table layui-form">
                <colgroup>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col width="240">
                </colgroup>
                <thead>
                <tr>
                    <th>编号</th>
                    <th>日志类型</th>
                    <th>会员ID</th>
                    <th>昵称</th>
                    <th>备注</th>
                    <th>操作人</th>
                    <th>操作时间</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($list as $item) { ?>
                    <tr data-id="<?= $item['id'] ?>">
                        <td><?= $item['id'] ?></td>
                        <td><?= $item['type'] == 1 ? "禁言" : ($item['type'] == 2 ? "锁定用户" : ($item['type'] == 3 ? "解锁用户" : ($item['type'] == 4 ? "冻结余额" : ($item['type'] == 5 ? "解冻余额" : '')))); ?></td>
                        <td><?= $item['user_id'] ?></td>
                        <td><?= $userInfos[$item['user_id']]['nickname'] ?></td>
                        <td><?= $item['remarks'] ?></td>
                        <td><?= $adminInfos[$item['admin_id']]['nickname'] ?></td>
                        <td><?= date('Y-m-d H:i:s', $item['addtime']) ?></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            <?= $page ?>
        </div>
    </div>
</div>

<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.extend({
        autocomplete: '/layuiadmin/autocomplete/autocomplete'
    }).use(['form', 'autocomplete', 'laydate'], function () {
        var $ = layui.$
            , form = layui.form
            , laydate = layui.laydate
            , autocomplete = layui.autocomplete;


        //开始日期
        var insStart = laydate.render({
            elem: '#addtime'
            , done: function (value, date) {
                //更新结束日期的最小日期
                insEnd.config.min = lay.extend({}, date, {
                    month: date.month - 1
                });

                //自动弹出结束日期的选择器
                insEnd.config.elem[0].focus();
            }
        });

        //结束日期
        var insEnd = laydate.render({
            elem: '#endtime'
            , done: function (value, date) {
                //更新开始日期的最大日期
                insStart.config.max = lay.extend({}, date, {
                    month: date.month - 1
                });
            }
        });
    });
</script>
</body>
</html>
