<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>
<body>
<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-form layui-card-header layuiadmin-card-header-auto">
            <div class="layui-form-item">
                <div class="layui-col-xs2">
                    <div class="layui-inline">
                        <a class="layui-btn layui-btn-primary" href="/block_device/index?p=<?= $p ?>">返回</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="layui-card-body">
            <table class="layui-table layui-form" id="table_id">
                <colgroup>
                    <col>
                    <col>
                    <col>
                    <col>
                </colgroup>
                <thead>
                <tr>
                    <th>操作时间</th>
                    <th>动作</th>
                    <th>备注</th>
                    <th>操作人</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($list as $item) { ?>
                    <tr data-id="<?= $item['id'] ?>">
                        <td><?= date("Y-m-d H:i:s", $item['addtime']) ?></td>
                        <td><?= $item['type'] == 1 ? "添加设备黑名单" : ($item['type'] == 2 ? "再次封禁" : "解除封禁") ?></td>
                        <td><?= $item['remarks'] ?></td>
                        <td><?= $adminInfos[$item['admin_id']]['nickname'] ?></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            <?= $page ?>
        </div>
    </div>
</div>
<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.extend({
        autocomplete: '/layuiadmin/autocomplete/autocomplete'
    }).use(['form', 'autocomplete', 'table'], function () {
        var $ = layui.$,
            autocomplete = layui.autocomplete,
            form = layui.form;

    });
</script>
</body>
</html>
