<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>
<body>
<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-form layui-card-header layuiadmin-card-header-auto">
            <div class="layui-form-item">
                <form method="get">
                    <div class="layui-col-xs2">
                        <div class="layui-inline"><a class="layui-btn" id="batchdel">一键删除</a></div>
                    </div>
                    <div class="layui-col-xs10 text-right">
                        <div class="layui-inline">
                            <input type="text" name="startdate" id="startdate" value="<?= $startdate ?>" placeholder="开始日期"
                                   autocomplete="off" class="layui-input">
                        </div>
                        <div class="layui-inline">
                            <input type="text" name="enddate" id="enddate" value="<?= $enddate ?>" placeholder="结束日期"
                                   autocomplete="off" class="layui-input">
                        </div>
                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-list" type="submit">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="layui-card-body">
            <table class="layui-table layui-form">
                <colgroup>
                    <col width="40">
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col width="150">
                </colgroup>
                <thead>
                <tr>
                    <th><input type="checkbox" lay-filter="check-all" lay-skin="primary"></th>
                    <th>ID</th>
                    <th>用户</th>
                    <th>类型</th>
                    <th>设备码</th>
                    <th>IP</th>
                    <th>相关游戏</th>
                    <th>联系方式</th>
                    <th>图片</th>
                    <th>反馈内容</th>
                    <th>回复内容</th>
                    <th>反馈时间</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($list as $item) { ?>
                    <tr data-id="<?= $item['id'] ?>">
                        <td><input type="checkbox" name="ids" lay-skin="primary" value="<?= $item['id'] ?>"></td>
                        <td><?= $item['id'] ?></td>
                        <td><?= $users[$item['user_id']]['username'] ?? '' ?>(<?= $item['user_id'] ?>)</td>
                        <td><?= $options[$item['type']]['name'] ?? '' ?></td>
                        <td><?= $item['imei'] ?></td>
                        <td><?= !empty($item['ip']) ? long2ip($item['ip']) : '' ?></td>
                        <td><?= $item['game_name'] ?></td>
                        <td><?= $item['contact'] ?></td>
                        <td style="padding: 2px; "><?php $imgs = json_decode($item['imgs']);
                            foreach ($imgs as $key => $img) { ?>
                                <img class="avartatPreview" data-src="<?= $img ?>" style="width: 30px;height: 30px;<?= $key > 1 ? 'display:none;"' : '' ?>"
                                     src="<?= $img ?>?x-oss-process=image/resize,m_fill,h_26,w_26"/>
                            <?php } ?>
                        </td>
                        <td>
                            <span class="view-detail">【详情】</span>
                            <?= mb_strimwidth($item['content'], 0, 15, '...') ?>
                            <textarea class="layui-textarea" style="display:none;height: 456px"><?= $item['content'] ?></textarea>
                        </td>
                        <td>
                            <span class="view-detail"><?= !empty($item['reply']) ? '【详情】' : '' ?></span>
<!--                            --><?//= mb_strimwidth($item['reply'], 0, 20, '...') ?>
                            <textarea class="layui-textarea"
                                      style="display:none;height: 456px"><?= $item['reply'] ?></textarea>
                        </td>
                        <td><?= $item['addtime'] > 0 ? date('Y-m-d H:i', $item['addtime']) : '' ?></td>
                        <td>
                            <?php if (!$item['state']) { ?>
                                <a class="layui-btn layui-btn-xs reply"><i class="layui-icon layui-icon-edit"></i>回复</a>
                            <?php } ?>
                            <a class="layui-btn layui-btn-danger layui-btn-xs delete"><i
                                        class="layui-icon layui-icon-delete"></i>删除</a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            <?= $page ?>
        </div>
    </div>
</div>

<!--回复弹出框-->
<div class="layui-form" id="feedback-reply" style="padding:20px;display: none">
    <div class="layui-form-item layui-col-md6">
        <div class="layui-input-inline">
            <textarea class="layui-textarea" name="reply" style="width: 400px;"></textarea>
        </div>
    </div>
    <div class="layui-form-item layui-col-md10">
        <div class="layui-input-inline">
            <input type="hidden" name="id" value="" id="id">
            <button class="layui-btn" lay-submit lay-filter="feedback-reply-submit">提交</button>
        </div>
    </div>
</div>


<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.use(['form', 'laydate'], function () {
        var $ = layui.$
            , form = layui.form
            , layer = layui.layer
            , laydate = layui.laydate;

        //全选
        form.on('checkbox(check-all)', function (data) {
            $('input[name="ids"]').prop("checked", data.elem.checked);
            form.render('checkbox');
        });

        //图片预览
        $('.avartatPreview').on('click', function () {
            var imgs = [];
            var avartas = $(this).closest('td').find('.avartatPreview');
            avartas.each(function (index, elem) {
                imgs.push({"src": elem.getAttribute('data-src')})
            })
            console.log(imgs)
            layer.photos({
                photos: {"data": imgs}
                , shade: 0.01
                , closeBtn: 1
                , anim: 5
            });
        })


        //查看错误详情
        $('.view-detail').click(function () {
            layer.open({
                title: '详情'
                , type: 1
                //,skin: 'layui-layer-rim'
                , shadeClose: true
                , area: ['700px', '500px']
                , content: $(this).closest('td').find('textarea')
            });
        });

        //回复
        $('.reply').click(function () {
            var id = $(this).closest('tr').data('id');
            $('#id').val(id);
            $('textarea[name="reply"]').val('');
            console.log(id)
            layer.open({
                title: '回复'
                , type: 1
                //,skin: 'layui-layer-rim'
                , shadeClose: true
                , area: ['450px', '260px']
                , content: $('#feedback-reply'),
            });
        });

        //提交回复
        form.on('submit(feedback-reply-submit)', function (obj) {
            $.ajax({
                url: '/feedback/reply',
                type: "POST",
                dataType: "JSON",
                data: obj.field,
                success: function (resp) {
                    if (resp.code == 200) {
                        layer.msg('操作成功', {icon: 1, time: 1000}, function () {
                            setTimeout(function () {
                                window.location.reload();
                            }, 1000)
                        });
                    } else {
                        layer.msg(resp.msg, {icon: 5, time: 1000});
                    }
                }
            })
        });

        //批量删除
        $('#batchdel').on('click', function () {
            var ids = [];
            $('input[name="ids"]:checked').each(function () {
                ids.push($(this).val())
            });
            if (ids.length <= 0) {
                layer.msg('请先选择记录', {icon:5, time:1000});
                return false;
            }
            layer.confirm('确定要删除吗？', {btn: ['确定', '取消']}, function () {
                batchdel(ids, function () {
                    location.href = location.href;
                });
            });

        });

        function batchdel(ids, callback) {
            $.ajax({
                type: "post",
                dataType: "json",
                url: "/feedback/delete",
                data: {"ids": ids},
                success: function (json) {
                    if (json.code == 200) {
                        layer.msg('删除成功', {icon: 1, time: 1000}, function () {
                            if (typeof callback == 'function') {
                                callback();
                            }
                        });
                    } else {
                        layer.alert(json.msg)
                    }
                }
            })
        }

        //单个删除
        $('.delete').on('click', function () {
            var ids = [];
            var tr = $(this).closest('tr');
            ids.push(tr.data('id'));
            layer.confirm('确定要删除吗？', {btn: ['确定', '取消']}, function () {
                batchdel(ids, function () {
                    tr.remove();
                });
            });
        });

        //开始日期
        var insStart = laydate.render({
                elem: '#startdate',
                done: function (value, date) {
                    //更新结束日期的最小日期
                    insEnd.config.min = lay.extend({}, date, {
                        month: date.month - 1
                    });

                    //自动弹出结束日期的选择器
                    insEnd.config.elem[0].focus();
                }
            })
        ;

        //结束日期
        var insEnd = laydate.render({
            elem: '#enddate',
            done: function (value, date) {
                //更新开始日期的最大日期
                insStart.config.max = lay.extend({}, date, {
                    month: date.month - 1
                });
            }
        });
    });
</script>
</body>
</html>
