<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>
<body>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">编辑分类</div>
                <div class="layui-card-body" pad15>
                    <div class="layui-form" lay-filter="">
                        <div class="layui-form-item">
                            <label class="layui-form-label">分类名称</label>
                            <div class="layui-input-inline">
                                <input type="text" name="name" value="<?= $info['name'] ?>" lay-verify="required"
                                       lay-verType="tips" autocomplete="off" class="layui-input">
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">所属主题</label>
                            <div class="layui-input-inline">
                                <select name="topic_id">
                                    <option value="">请选主题</option>
                                    <?php foreach ($topics as $topic) { ?>
                                        <option value="<?= $topic['id'] ?>" <?= $info['topic_id'] == $topic['id'] ? 'selected' : '' ?>><?= $topic['name'] ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">显示状态</label>
                            <div class="layui-input-block">
                                <input type="radio" name="status" value="1"
                                       title="正常" <?= $info['status'] == 1 ? 'checked' : '' ?>>
                                <input type="radio" name="status" value="0"
                                       title="关闭" <?= $info['status'] == 0 ? 'checked' : '' ?>>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <input type="hidden" name="id" value="<?= $info['id'] ?>">
                                <button class="layui-btn" lay-submit lay-filter="game-cate-edit">提交</button>
                                <a class="layui-btn layui-btn-primary" href="/game_cate/index?p=<?= $p ?>">返回</a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.use('form', function () {
        var $ = layui.$
            , form = layui.form
            , layer = layui.layer;

        /*form.verify({
            nickname: [/^[\S]{2,16}$/, '昵称最少2个字符'],
        })*/

        form.on('submit(game-cate-edit)', function (obj) {
            $.ajax({
                url: '/game_cate/edit',
                type: "POST",
                dataType: "JSON",
                data: obj.field,
                success: function (resp) {
                    if (resp.code == 200) {
                        layer.msg('修改成功', {icon: 1, time: 1000}, function () {
                            location.href = '/game_cate/index';
                        });
                    } else {
                        layer.msg(resp.msg, {icon: 5, time: 1000});
                    }
                }
            })
        });

    });
</script>
</body>
</html>