<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>
<body>
<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-form layui-card-header layuiadmin-card-header-auto layui-row">
            <div class="layui-col-xs2" style="width: 60%;">
                <div class="layui-inline"><a class="layui-btn search-time" data-val="1" href="#">所有时间</a></div>
                <div class="layui-inline"><a class="layui-btn search-time" data-val="2" href="#">本月</a></div>
                <div class="layui-inline"><a class="layui-btn search-time" data-val="3" href="#">上月</a></div>
                <div class="layui-inline"><a class="layui-btn search-time" data-val="4" href="#">最近30天</a></div>
                <div class="layui-inline"><a class="layui-btn search-time" data-val="5" href="#">最近3月</a></div>
                <div class="layui-inline"><a class="layui-btn search-time" data-val="6" href="#">最近6月</a></div>
                <div class="layui-inline"><a class="layui-btn search-time" data-val="7" href="#">最近9月</a></div>
                <div class="layui-inline"><a class="layui-btn search-time" data-val="8" href="#">最近12月</a></div>
                <div class="layui-inline"><a class="layui-btn layui-btn-primary" href="/coin_expense_log/index">返回</a></div>
            </div>
            <form method="get" id="search">
                <div class="text-right" style="float: right">
                    <div class="layui-inline" style="width: 120px;">
                        <input type="text" name="start_time" id="start_time" value="<?= $start_time ?>"
                               placeholder="开始日期" autocomplete="off" class="layui-input">
                    </div>
                    <span class="layui-inline">至</span>
                    <div class="layui-inline" style="width: 120px;">
                        <input type="text" name="end_time" id="end_time" value="<?= $end_time ?>"
                               placeholder="结束日期" autocomplete="off" class="layui-input">
                    </div>
                    <div class="layui-inline">
                        <button class="layui-btn layuiadmin-btn-list" type="submit">
                            <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <div class="layui-card-body">
            <table class="layui-table layui-form" id="table_id">
                <colgroup>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                </colgroup>
                <thead>
                <tr>
                    <th>用户ID</th>
                    <th>用户名</th>
                    <th>总金额</th>
                    <th>充值金额</th>
                    <th>活动获取</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($list as $item) { ?>
                    <tr data-id="<?= $item['id'] ?>">
                        <td><?= $item['id'] ?></td>
                        <td><?= $userInfos[$item['user_id']]['username'] ?? '' ?></td>
                        <td><?= $item['amount'] ?></td>
                        <td><?= $item['charge'] ?></td>
                        <td><?= $item['give'] ?></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            <?= $page ?>
        </div>
    </div>
</div>

<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.use(['form', 'laydate'], function () {
        var $ = layui.$,
            laydate = layui.laydate;

        function dateFormatConversion(inputTime) {
            var date = new Date(inputTime);
            var y = date.getFullYear();
            var m = date.getMonth() + 1;
            m = m < 10 ? ('0' + m) : m;
            var d = date.getDate();
            d = d < 10 ? ('0' + d) : d;
            return y + '-' + m + '-' + d;
        };

        $('.search-time').on('click', function () {
            var d = new Date();
            var currentYear = d.getFullYear();
            var currentMonth = d.getMonth();
            var currentDay = d.getDate();

            var type = $(this).data('val');
            var start_time = '', end_time = '';
            if (type == 2) {   // 本月
                start_time = dateFormatConversion(new Date(currentYear, currentMonth, 1).getTime()); // 获取本月第一天
                end_time = dateFormatConversion(new Date(currentYear, currentMonth + 1, 0).getTime()); // 获取本月最后一天
            } else if (type == 3) { // 上月
                d.setMonth(d.getMonth() - 1);
                start_time = dateFormatConversion(new Date(d.getFullYear(), d.getMonth(), 1));
                end_time = dateFormatConversion(new Date(d.getFullYear(), d.getMonth() + 1, 0));
            } else if (type == 4) { // 最近30天
                d.setDate(d.getDate() - 30);
                start_time = dateFormatConversion(new Date(d.toLocaleDateString()));
                end_time = dateFormatConversion(new Date(currentYear, currentMonth, currentDay));
            } else if (type == 5) { // 最近3月
                d.setMonth(d.getMonth() - 3);
                start_time = dateFormatConversion(new Date(d.toLocaleDateString()));
                end_time = dateFormatConversion(new Date(currentYear, currentMonth, currentDay));
            } else if (type == 6) { // 最近6月
                d.setMonth(d.getMonth() - 6);
                start_time = dateFormatConversion(new Date(d.toLocaleDateString()));
                end_time = dateFormatConversion(new Date(currentYear, currentMonth, currentDay));
            } else if (type == 7) { // 最近9月
                d.setMonth(d.getMonth() - 9);
                start_time = dateFormatConversion(new Date(d.toLocaleDateString()));
                end_time = dateFormatConversion(new Date(currentYear, currentMonth, currentDay));
            } else if (type == 8) { // 最近12月
                d.setMonth(d.getMonth() - 12);
                start_time = dateFormatConversion(new Date(d.toLocaleDateString()));
                end_time = dateFormatConversion(new Date(currentYear, currentMonth, currentDay));
            }
            $("#start_time").val(start_time);
            $("#end_time").val(end_time);
            $('#search').submit();
        });

        //开始日期
        var insStart = laydate.render({
            elem: '#start_time'
            , done: function (value, date) {
                //更新结束日期的最小日期
                insEnd.config.min = lay.extend({}, date, {
                    month: date.month - 1
                });

                //自动弹出结束日期的选择器
                insEnd.config.elem[0].focus();
            }
        });

        //结束日期
        var insEnd = laydate.render({
            elem: '#end_time'
            , done: function (value, date) {
                //更新开始日期的最大日期
                insStart.config.max = lay.extend({}, date, {
                    month: date.month - 1
                });
            }
        });
    });
</script>
</body>
</html>
