<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>
<body>
<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-form layui-card-header layuiadmin-card-header-auto">
            <div class="layui-form-item">
                <form method="get">
                    <div class="layui-col-xs2">
                        <div class="layui-inline">
                            <a class="layui-btn" href="/invoice/add">添加发票</a>
                        </div>
                    </div>
                    <div class="layui-col-xs10 text-right">
                        <div class="layui-inline">
                            <input type="text" name="name" id="name" value="<?= $name ?? ''; ?>"
                                   class="layui-input" placeholder="公司名称" autocomplete="off">
                        </div>
                        <div class="layui-inline">
                            <input type="text" name="number" id="number" value="<?= $number ?? ''; ?>"
                                   class="layui-input" placeholder="发票号码" autocomplete="off">
                        </div>
                        <div class="layui-inline text-left" style="width: 120px;">
                            <select name="type">
                                <option value="">发票类型</option>
                                <option value="1" <?= $type == 1 ? 'selected' : '' ?>>专用发票</option>
                                <option value="2" <?= $type == 2 ? 'selected' : '' ?>>普通发票</option>
                            </select>
                        </div>
                        <div class="layui-inline text-left" style="width: 120px;">
                            <select name="admin_id">
                                <option value="">录入者</option>
                                <?php foreach ($adminList as $item) {?>
                                <option value="<?= $item['id'] ?>" <?= $admin_id == $item['id'] ? 'selected' : '' ?>><?= $item['nickname'] ?></option>
                                <?php } ?>
                            </select>
                        </div>
                        <div class="layui-inline text-left" style="width: 120px;">
                            <input type="text" name="start_time" id="startdate" value="<?= $start_time ?? '' ?>"
                                   placeholder="开始日期" autocomplete="off" class="layui-input">
                        </div>
                        <div class="layui-inline text-left">
                            -
                        </div>
                        <div class="layui-inline text-left" style="width: 120px;">
                            <input type="text" name="end_time" id="enddate" value="<?= $end_time ?? '' ?>"
                                   placeholder="结束日期" autocomplete="off" class="layui-input">
                        </div>
                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-list" type="submit">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="layui-row highlight-block">
            <div class="layui-col-md12">
                发票总额：<span><?= $total_money ?? 0 ?> 元</span>
                专用发票：<span><?= $special_total_money ?? 0 ?> 元</span>
                普通发票：<span><?= $general_total_money ?? 0 ?> 元</span>
            </div>
        </div>
        <div class="layui-card-body">
            <table class="layui-table layui-form">
                <colgroup>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col width="160">
                </colgroup>
                <thead>
                <tr>
                    <th>编号</th>
                    <th>公司名称</th>
                    <th>发票类型</th>
                    <th>金额</th>
                    <th>对应订单金额</th>
                    <th>发票代码</th>
                    <th>发票号码</th>
                    <th>开票日期</th>
                    <th>备注</th>
                    <th>录入者</th>
                    <th>录入时间</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($list as $item) { ?>
                    <tr data-id="<?= $item['id'] ?>">
                        <td><?= $item['id'] ?></td>
                        <td><?= $item['name'] ?></td>
                        <td><?= $item['type'] == 1 ? '专用发票' : ($item['type'] == 2 ? '普通发票' : '') ?></td>
                        <td><?= $item['amount'] ?></td>
                        <td><?= $item['order_amount'] ?></td>
                        <td><?= $item['imei'] ?></td>
                        <td><?= $item['number'] ?></td>
                        <td><?= $item['time'] != 0 ? date('Y-m-d H:i:s', $item['time']) : '' ?></td>
                        <td><?= $item['remarks'] ?></td>
                        <td><?= $adminInfos[$item['admin_id']]['nickname'] ?? '' ?></td>
                        <td><?= date('Y-m-d H:i:s', $item['addtime']) ?></td>
                        <td>
                            <a class="layui-btn layui-btn-xs" href="/invoice/edit?id=<?= $item['id'] ?>&p=<?= $p ?>">
                                <i class='layui-icon layui-icon-edit'></i>编辑</i>
                            </a>
                            <a class="layui-btn layui-btn-xs delete">
                                <i class='layui-icon layui-icon-delete'></i>删除</i>
                            </a>
                        </td>

                    </tr>
                <?php } ?>
                </tbody>
            </table>
            <?= $page ?>
        </div>
    </div>
</div>
<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.extend({
        autocomplete: '/layuiadmin/autocomplete/autocomplete'
    }).use(['form', 'autocomplete', 'laydate'], function () {
        var $ = layui.$
            , form = layui.form
            , laydate = layui.laydate
            , autocomplete = layui.autocomplete;

        $('.delete').on('click', function () {
            var tr = $(this).closest('tr');
            var id = tr.data('id');
            console.log(id);
            $.ajax({
                type: 'POST',
                dataType: 'JSON',
                url: '/invoice/delete',
                data: {'id': id},
                success: function (json) {
                    if (json.code == 200) {
                        layer.msg('删除成功', {icon: 1, time: 1000}, function () {
                            tr.remove();
                        });
                    } else {
                        layer.msg(json.msg, {icon: 5, time:1000});
                    }
                }
            })
        });

        // 搜索发票公司名称
        autocomplete.init({
            elem: "#name",
            textLength: 2,//触发长度
            delay: 200,//触发延迟
            callback: {
                data: function (val, render) {
                    $.ajax({
                        type: "post",
                        dataType: "json",
                        url: "/invoice/autocomplete",
                        data: {name: val},
                        success: function (json) {
                            if (json.code == 200) {
                                render(json.data);
                            } else {
                                layer.alert(json.msg);
                            }
                        }
                    });
                },
                // selected: function (data) {
                //     $('#name').val(data.title)
                // },
                // close: function () {
                //
                // }
            }
        });

        // 搜索发票号码
        autocomplete.init({
            elem: "#number",
            textLength: 2,//触发长度
            delay: 200,//触发延迟
            callback: {
                data: function (val, render) {
                    $.ajax({
                        type: "post",
                        dataType: "json",
                        url: "/invoice/autocomplete_number",
                        data: {name: val},
                        success: function (json) {
                            if (json.code == 200) {
                                render(json.data);
                            } else {
                                layer.alert(json.msg);
                            }
                        }
                    });
                },
                // selected: function (data) {
                //     // console.log(data)
                //     // $('#number').val(data.title)
                // },
                // close: function () {
                //
                // }
            }
        });

        //开始日期
        var insStart = laydate.render({
            elem: '#startdate'
            , done: function (value, date) {
                //更新结束日期的最小日期
                insEnd.config.min = lay.extend({}, date, {
                    month: date.month - 1
                });

                //自动弹出结束日期的选择器
                insEnd.config.elem[0].focus();
            }
        });

        //结束日期
        var insEnd = laydate.render({
            elem: '#enddate'
            , done: function (value, date) {
                //更新开始日期的最大日期
                insStart.config.max = lay.extend({}, date, {
                    month: date.month - 1
                });
            }
        });

    });
</script>
</body>
</html>
