<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>
<body>

<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">编辑礼包</div>
                <div class="layui-card-body" pad15>
                    <div class="layui-form" lay-filter="">
                        <input type="hidden" name="id" value="<?= $info['id'] ?>">
                        <div class="layui-form-item">
                            <label class="layui-form-label">礼包名称</label>
                            <div class="layui-input-inline">
                                <input type="text" name="name" value="<?= $info['name'] ?>" lay-verify="required"
                                       lay-verType="tips"
                                       autocomplete="off" class="layui-input">
                            </div>
                        </div>

                        <div class="layui-form-item">
                            <label class="layui-form-label">礼包类型</label>
                            <div class="layui-input-inline">
                                <select name="type_id">
                                    <option value="">请选类型</option>
                                    <?php foreach ($giftType as $value) { ?>
                                        <option value="<?= $value['id'] ?>" <?= $info['type_id'] == $value['id'] ? 'selected = "selected"' : ''?> ><?= $value['name'] ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>

                        <div class="layui-form-item">
                            <label class="layui-form-label">所属游戏</label>
                            <div class="layui-input-inline">
                                <input type="hidden" name="game_id" value="<?= $info['game_id'] ?>">
                                <input type="text" name="game_name" id="game_name" value="<?= $game_name ?>"
                                       class="layui-input" placeholder="游戏名称" autocomplete="off">
                            </div>
                        </div>

                        <div class="layui-form-item">
                            <label class="layui-form-label">适用系统</label>
                            <div class="layui-input-block">
                                <input type="radio" name="platform"
                                       value="0" <?= $info['platform'] == 0 ? 'checked' : '' ?> title="通用系统">
                                <input type="radio" name="platform"
                                       value="1" <?= $info['platform'] == 1 ? 'checked' : '' ?> title="安卓">
                                <input type="radio" name="platform"
                                       value="2" <?= $info['platform'] == 2 ? 'checked' : '' ?> title="IOS">
                            </div>
                        </div>

                        <div class="layui-form-item">
                            <label class="layui-form-label">有效时间</label>
                            <div class="layui-input-block">
                                <div class="layui-inline">
                                    <input type="text" name="start_time" id="start_time" value="<?= date('Y-m-d', $info['start_time']) ?>"
                                           placeholder="开始日期" autocomplete="off" class="layui-input">
                                </div>
                                <div class="layui-inline">
                                    <span>至</span>
                                </div>
                                <div class="layui-inline">
                                    <input type="text" name="end_time" id="end_time" value="<?= date('Y-m-d', $info['end_time']) ?>"
                                           placeholder="结束日期" autocomplete="off" class="layui-input">
                                </div>
                            </div>
                        </div>

                        <div class="layui-form-item">
                            <label class="layui-form-label">设备限制</label>
                            <div class="layui-input-inline">
                                <input type="radio" name="device_only"
                                       value="1" <?= $info['device_only'] == 1 ? "checked" : '' ?> title="是">
                                <input type="radio" name="device_only"
                                       value="0" <?= $info['device_only'] == 0 ? "checked" : '' ?> title="否">
                            </div>
                            <div class="layui-form-mid layui-word-aux">（如果设备限制选“是”，表示一个设备只能领取一个礼包）</div>
                        </div>

                        <div class="layui-form-item">
                            <label class="layui-form-label">通用卡号</label>
                            <div class="layui-input-inline">
                                <input type="text" name="is_common" value="<?= $info['is_common'] ?>"
                                       lay-verify="required" disabled="disabled" lay-verType="tips" autocomplete="off" class="layui-input">
                            </div>
                            <div class="layui-form-mid layui-word-aux">（默认为0，表示卡号不通用；如果设值，代表通用的数量）</div>
                        </div>

                        <div class="layui-form-item">
                            <label class="layui-form-label">礼包内容</label>
                            <div class="layui-input-block">
                               <textarea name="des" lay-verify="required" placeholder="请输入"
                                         class="layui-textarea"><?= $info['des'] ?></textarea>
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>

                        <div class="layui-form-item">
                            <label class="layui-form-label">使用方法</label>
                            <div class="layui-input-block">
                               <textarea name="usage" lay-verify="required" placeholder="请输入"
                                         class="layui-textarea"><?= $info['usage'] ?></textarea>
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>

                        <div class="layui-form-item">
                            <label class="layui-form-label">礼包状态</label>
                            <div class="layui-input-inline">
                                <input type="radio" name="status" value="1" <?= $info['status'] == 1 ? "checked" : '' ?>
                                       title="正常">
                                <input type="radio" name="status" value="0" <?= $info['status'] == 0 ? "checked" : '' ?>
                                       title="关闭">
                            </div>
                        </div>

                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <button class="layui-btn" lay-submit lay-filter="gift-edit">提交</button>
                                <a class="layui-btn layui-btn-primary" href="/gift/index?p=<?= $p ?>">返回</a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script type="text/javascript" src="/common/js/plupload-2.1.2/js/plupload.full.min.js"></script>
<script type="text/javascript" src="/common/js/oss.upload.lib.js?t=20190402"></script>
<script>
    layui.extend({
        autocomplete: '/layuiadmin/autocomplete/autocomplete'
    }).use(['form', 'laydate', 'autocomplete'], function () {
        var $ = layui.$,
            form = layui.form,
            laydate = layui.laydate,
            autocomplete = layui.autocomplete,
            layer = layui.layer;

        form.on('submit(gift-edit)', function (obj) {
            $.ajax({
                url: '/gift/edit',
                type: "POST",
                dataType: "JSON",
                data: obj.field,
                success: function (resp) {
                    if (resp.code == 200) {
                        layer.msg('编辑成功', {icon: 1, time: 1000}, function () {
                            location.href = '/gift/index';
                        });
                    } else {
                        layer.msg(resp.msg, {icon: 5, time: 1000});
                    }
                }
            })
        });

        //搜索游戏
        $('#game_name').on('keydown', function (event) {
            if (event.keyCode == 8) {
                $('input[name="game_id"]').val('')
            }
        });
        autocomplete.init({
            elem: "#game_name",
            textLength: 2,//触发长度
            delay: 200,//触发延迟
            callback: {
                data: function (val, render) {
                    $.ajax({
                        type: "post",
                        dataType: "json",
                        url: "/game/autocomplete",
                        data: {name: val},
                        success: function (json) {
                            if (json.code == 200) {
                                render(json.data);
                            } else {
                                layer.alert(json.msg);
                            }
                        }
                    });
                },
                selected: function (data) {
                    console.log(data)
                    $('input[name="game_id"]').val(data.value)
                },
                close: function () {
                }
            }
        });


        //开始日期
        var insStart = laydate.render({
            elem: '#start_time'
            , done: function (value, date) {
                //更新结束日期的最小日期
                insEnd.config.min = lay.extend({}, date, {
                    month: date.month - 1
                });

                //自动弹出结束日期的选择器
                insEnd.config.elem[0].focus();
            }
        });

        //结束日期
        var insEnd = laydate.render({
            elem: '#end_time'
            , done: function (value, date) {
                //更新开始日期的最大日期
                insStart.config.max = lay.extend({}, date, {
                    month: date.month - 1
                });
            }
        });
    });
</script>
</body>
</html>