<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>
<body>
<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-card-body">
            <div class="layui-form layui-card-header layuiadmin-card-header-auto layui-row">
                <div class="layui-form-item">
                    <div class="layui-col-xs2">
                        <a class="layui-btn" href="/gift/add">添加</a>
                    </div>
                    <form method="get">
                        <div class="layui-col-xs10 text-right">
                            <div class="layui-inline">
                                <input type="hidden" name="game_id" value="<?= $game_id ?>">
                                <input type="text" name="game_name" id="game_name" value="<?= $game_name ?>" class="layui-input"
                                       placeholder="请输入游戏名称" autocomplete="off">
                            </div>
                            <div class="layui-inline">
                                <button class="layui-btn layuiadmin-btn-list" type="submit">
                                    <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <table class="layui-table layui-form">
                <colgroup>
                    <col width="80">
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col width="260">
                </colgroup>
                <thead>
                <tr>
                    <th>礼包ID</th>
                    <th>礼包名称</th>
                    <th>礼包类型</th>
                    <th>所属游戏</th>
                    <th>系统平台</th>
                    <th>礼包总数</th>
                    <th>剩余数</th>
                    <th>添加时间</th>
                    <th>有效期</th>
                    <th>周领号数</th>
                    <th>月领号数</th>
                    <th>状态</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($list as $item) { ?>
                    <tr data-id="<?= $item['id'] ?>">
                        <td><?= $item['id'] ?></td>
                        <td><?= $item['name'] ?></td>
                        <td><?= $giftType[$item['type_id']]['name'] ?? '' ?></td>
                        <td><?= $gameInfos[$item['game_id']]['name'] ?? '' ?></td>
                        <td><?= $item['platform'] == 0 ? '通用' : ($item['platform'] == 1 ? '安卓' : 'IOS') ?></td>
                        <td><?= $item['total'] ?></td>
                        <td><?= $item['total'] - $item['receive_count'] ?></td>
                        <td><?= date('Y-m-d H:i:s', $item['addtime']) ?></td>
                        <td><?= $item['end_time'] >0 ? date('Y-m-d H:i:s', $item['end_time'])  : '' ?></td>
                        <td><?= $item['weekNum'] ?></td>
                        <td><?= $item['monthNum'] ?></td>
                        <td><input type="checkbox" value="1" lay-filter="status"
                                   name="status" <?= ($item['status'] == 1) ? 'checked' : '' ?> lay-skin="switch"
                                   lay-text="开启|关闭"></td>
                        <td>
                            <a class="layui-btn layui-btn-xs" href="/gift/edit?id=<?= $item['id'] ?>&p=<?= $p ?>">
                                <i class="layui-icon layui-icon-edit"></i>编辑
                            </a>
                            <a class="layui-btn layui-btn-xs" href="/gift_code/index?id=<?= $item['id'] ?>&last_page=<?= $p ?>">
                                管理兑换码
                            </a>
                            <a class="layui-btn layui-btn-xs layui-btn-danger delete">
                                <i class="layui-icon layui-icon-delete"></i>移除
                            </a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            <?= $page ?>
        </div>
    </div>
</div>

<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.extend({
        autocomplete: '/layuiadmin/autocomplete/autocomplete'
    }).use(['form', 'autocomplete'], function () {
        var $ = layui.$,
            autocomplete = layui.autocomplete,
            form = layui.form;

        //搜索游戏
        $('#game_name').on('keydown', function (event) {
            if (event.keyCode == 8) {
                $('input[name="game_id"]').val('')
            }
        });
        autocomplete.init({
            elem: "#game_name",
            textLength: 2,//触发长度
            delay: 200,//触发延迟
            callback: {
                data: function (val, render) {
                    $.ajax({
                        type: "post",
                        dataType: "json",
                        url: "/game/autocomplete",
                        data: {name: val},
                        success: function (json) {
                            if (json.code == 200) {
                                render(json.data);
                            } else {
                                layer.alert(json.msg);
                            }
                        }
                    });
                },
                selected: function (data) {
                    console.log(data);
                    $('input[name="game_id"]').val(data.value)
                },
                close: function () {
                }
            }
        });

        //启用禁用
        form.on('switch(status)', function (data) {
            console.log(data.elem.checked);
            var id = $(this).closest('tr').data('id');
            var status = data.elem.checked ? 1 : 0;
            $.ajax({
                type: "post",
                dataType: "json",
                url: "/gift/toggle",
                data: {id: id, status: status},
                success: function (json) {
                    if (json.code == 200) {
                        layer.msg('操作成功');
                    } else {
                        layer.alert(json.msg);
                    }
                }
            });
        });

        function batchdel(ids, callback) {
            $.ajax({
                type: "post",
                dataType: "json",
                url: "/gift/delete",
                data: {"ids": ids},
                success: function (json) {
                    if (json.code == 200) {
                        layer.msg('删除成功', {icon: 1, time: 1000}, function () {
                            if (typeof callback == 'function') callback();
                        });
                    } else {
                        layer.alert(json.msg)
                    }
                }
            })
        }

        //单个删除
        $('.delete').on('click', function () {
            var ids = [];
            var tr = $(this).closest('tr');
            ids.push(tr.data('id'));
            layer.confirm('确定要删除吗？', {btn: ['确定', '取消']}, function () {
                batchdel(ids, function () {
                    tr.remove();
                });
            });
        });


    });
</script>
</body>
</html>
