<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>
<body>

<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">修改版本</div>
                <div class="layui-card-body" pad15>

                    <div class="layui-form" lay-filter="">
                        <div class="layui-form-item">
                            <label class="layui-form-label">新版本号</label>
                            <div class="layui-input-inline">
                                <input type="text" name="version" value="<?=$info['version']?>" lay-verify="required" lay-verType="tips"  autocomplete="off" class="layui-input">
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">新版大小</label>
                            <div class="layui-input-inline">
                                <input type="text" name="size" value="<?=$info['size']?>" lay-verify="required" lay-verType="tips" autocomplete="off"  class="layui-input">
                            </div>
                            <div class="layui-form-mid layui-word-aux">M</div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">安卓母包</label>
                            <div class="layui-input-inline">
                                <input type="text" name="origin_package_android" value="<?=$info['origin_package_android']?>" lay-verify="url" lay-verType="tips" autocomplete="off" class="layui-input">
                            </div>
                            <div class="layui-input-inline" id="container">
                                <button type="button" class="layui-btn layui-btn-primary" id="origin_package_android">上传文件</button>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">iOS母包</label>
                            <div class="layui-input-inline">
                                <input type="text" name="origin_package_ios" value="<?=$info['origin_package_ios']?>" lay-verify="url" lay-verType="tips" autocomplete="off" class="layui-input">
                            </div>
                            <div class="layui-input-inline" id="container_ios">
                                <button type="button" class="layui-btn layui-btn-primary" id="origin_package_ios">上传文件</button>
                            </div>
                        </div>

                        <div class="layui-form-item">
                            <label class="layui-form-label">iOS描述文件</label>
                            <div class="layui-input-inline">
                                <input type="text" name="plist_url" value="<?=$info['plist_url']?>" lay-verify="url" lay-verType="tips" autocomplete="off" class="layui-input">
                            </div>
                            <div class="layui-input-inline" id="container_plist">
                                <button type="button" class="layui-btn layui-btn-primary" id="plist_url">上传文件</button>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">版本描述</label>
                            <div class="layui-input-block">
                                <textarea class="layui-textarea" name="des"><?=$info['des']?></textarea>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">强制更新</label>
                            <div class="layui-input-inline">
                                <input type="hidden" name="force_update" value="0">
                                <input type="checkbox" value="1" name="force_update" <?php if($info['force_update']){echo 'checked';}?> lay-skin="switch" lay-text="是|否">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <input type="hidden" value="<?=$info['id']?>" name="id">
                                <button class="layui-btn" lay-submit lay-filter="version-edit">提交</button>
                                <a class="layui-btn layui-btn-primary" href="/version/index?p=<?= $p ?>">返回</a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.use(['form', 'upload'], function () {
        var $ = layui.$
            , form = layui.form
            , layer = layui.layer
            , upload = layui.upload;

        /*form.verify({
            nickname: [/^[\S]{2,16}$/, '昵称最少2个字符'],
        })*/

        form.on('submit(version-edit)', function (obj) {
            $.ajax({
                url: '/version/edit',
                type: "POST",
                dataType: "JSON",
                data: obj.field,
                success: function (resp) {
                    if (resp.code == 200) {
                        layer.msg('修改成功', {icon: 1, time: 1000}, function () {
                            location.href = '/version/index';
                        });
                    } else {
                        layer.msg(resp.msg, {icon: 5, time: 1000});
                    }
                }
            })
        });

        //安卓包上传
        upload.render({ //允许上传的文件后缀
            elem: '#origin_package_android'
            , url: '<?=$upload_domain?>?dir=app&name_type=original'
            , accept: 'file' //普通文件
            , exts: 'apk' //只允许上传压缩文件
            , headers: <?=json_encode($headers)?>
            , before: function(obj){
                layer.load(); //上传loading
            }
            , done: function (resp) {
                if (resp.code == 200) {
                    $('input[name="origin_package_android"]').val(resp.data.urls[0]);
                } else {
                    //layer.msg('上传失败', {icon: 5, time: 1000});
                }
                layer.closeAll('loading'); //关闭loading
            }
            , error: function(index, upload){
                layer.closeAll('loading'); //关闭loading
            }
        });

        //IOS上传
        upload.render({ //允许上传的文件后缀
            elem: '#origin_package_ios'
            ,url: '<?=$upload_domain?>?dir=app&name_type=original'
            ,accept: 'file' //普通文件
            ,exts: 'ipa' //只允许上传压缩文件
            ,headers: <?=json_encode($headers)?>
            , before: function(obj){
                layer.load(); //上传loading
            }
            , done: function (resp) {
                if (resp.code == 200) {
                    $('input[name="origin_package_ios"]').val(resp.data.urls[0]);
                } else {
                    //layer.msg('上传失败', {icon: 5, time: 1000});
                }
                layer.closeAll('loading'); //关闭loading
            }
            , error: function(index, upload){
                layer.closeAll('loading'); //关闭loading
            }
        });

        //PLIST上传
        upload.render({ //允许上传的文件后缀
            elem: '#plist_url'
            ,url: '<?=$upload_domain?>?dir=app&name_type=original'
            ,accept: 'file' //普通文件
            ,exts: 'plist'
            ,headers: <?=json_encode($headers)?>
            , before: function(obj){
                layer.load(); //上传loading
            }
            , done: function (resp) {
                if (resp.code == 200) {
                    $('input[name="plist_url"]').val(resp.data.urls[0]);
                } else {
                    //layer.msg('上传失败', {icon: 5, time: 1000});
                }
                layer.closeAll('loading'); //关闭loading
            }
            , error: function(index, upload){
                layer.closeAll('loading'); //关闭loading
            }
        });
    });
</script>
</body>
</html>