<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>

<body>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">添加渠道</div>
                <div class="layui-card-body" pad15="">
                    <div class="layui-form" lay-filter="">
                        <div class="layui-form-item">
                            <label class="layui-form-label">渠道账号</label>
                            <div class="layui-input-inline">
                                <input type="text" name="username" value="" placeholder="请输入渠道账号"
                                       lay-verify="required" lay-verType="tips" autocomplete="off" class="layui-input">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">渠道密码</label>
                            <div class="layui-input-inline">
                                <input type="password" name="password" value="" placeholder="请输入渠道密码"
                                       lay-verify="required" lay-verType="tips" autocomplete="off" class="layui-input">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">确认渠道密码</label>
                            <div class="layui-input-inline">
                                <input type="password" name="password1" value="" placeholder="请重复渠道密码"
                                       lay-verify="required" lay-verType="tips" autocomplete="off" class="layui-input">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">渠道类型</label>
                            <div class="layui-input-block">
                                <input type="radio" name="type" value="1" title="可盘官方">
                                <input type="radio" name="type" value="2" title="第三方">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">结算方式</label>
                            <div class="layui-input-inline">
                                <select name="settlement_type"  lay-verify="required" lay-verType="tips">
                                    <option value="">请选择结算方式</option>
                                    <option value="1">CPC</option>
                                    <option value="2">CPS</option>
                                    <option value="3">工会</option>
                                </select>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">联系人</label>
                            <div class="layui-input-inline">
                                <input type="text" name="contact" value="" placeholder="请输入联系人姓名" autocomplete="off" class="layui-input">
                            </div>
                            <div class="layui-form-mid layui-word-aux">(选填)</div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">QQ</label>
                            <div class="layui-input-inline">
                                <input type="text" name="qq" value="" placeholder="请输入QQ号" autocomplete="off" class="layui-input">
                            </div>
                            <div class="layui-form-mid layui-word-aux">(选填)</div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">微信</label>
                            <div class="layui-input-inline">
                                <input type="text" name="wechat" value="" placeholder="请输入微信号" autocomplete="off" class="layui-input">
                            </div>
                            <div class="layui-form-mid layui-word-aux">(选填)</div>
                        </div>

                        <div class="layui-form-item">
                            <label class="layui-form-label">手机号码</label>
                            <div class="layui-input-inline">
                                <input type="text" name="mobile" value="" placeholder="请输入手机号" autocomplete="off" class="layui-input">
                            </div>
                            <div class="layui-form-mid layui-word-aux">(选填)</div>
                        </div>

                        <div class="layui-form-item">
                            <label class="layui-form-label">备注</label>
                            <div class="layui-input-inline" style="width: 600px">
                                <textarea name="remarks" placeholder="请输入备注" class="layui-textarea"></textarea>
                            </div>
                            <div class="layui-form-mid layui-word-aux">(选填)</div>
                        </div>

                        <div class="layui-form-item">
                            <label class="layui-form-label">状态</label>
                            <div class="layui-input-block">
                                <input type="radio" name="status" value="1" title="正常">
                                <input type="radio" name="status" checked value="0" title="关闭">
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>

                        <div class="layui-form-item">
                            <label class="layui-form-label">所属商务</label>
                            <div class="layui-input-inline">
                                <select name="business_id" lay-verify="required" lay-verType="tips">
                                    <option value="">请选择商务</option>
                                    <?php foreach ($business as $v) { ?>
                                        <option value="<?= $v['id'] ?>"><?= $v['nickname'] ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>

                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <button class="layui-btn" lay-submit lay-filter="channel-add">提交</button>
                                <a class="layui-btn layui-btn-primary" href="javascript:void(0);"
                                   onclick="history.go(-1)">返回</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script type="text/javascript" src="/common/js/plupload-2.1.2/js/plupload.full.min.js"></script>
<script type="text/javascript" src="/common/js/oss.upload.lib.js?t=20190402"></script>
<script>
    layui.use(['form', 'layer'], function () {
            var $ = layui.$,
                form = layui.form,
                layer = layui.layer;

            form.on('submit(channel-add)', function (obj) {
                $.ajax({
                    url: '/channel/add',
                    type: "POST",
                    dataType: "JSON",
                    data: obj.field,
                    success: function (resp) {
                        if (resp.code == 200) {
                            layer.msg('添加成功', {icon: 1, time: 1000}, function () {
                                location.href = '/channel/index';
                            });
                        } else {
                            layer.msg(resp.msg, {icon: 5, time: 1000});
                        }
                    }
                })
            });
        }
    );
</script>
</body>
</html>