<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>

<body>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">修改编辑</div>
                <div class="layui-card-body">
                    <div class="layui-tab layui-tab-brief" lay-filter="docDemoTabBrief">
                        <ul class="layui-tab-title">
                            <li class="<?= $tab == 1 ? 'layui-this' : '' ?>"><a
                                        href="/channel/info_edit?tab=1&id=<?= $id ?>&p=<?= $p ?>">基本信息</a></li>
                            <li class="<?= $tab == 2 ? 'layui-this' : '' ?>"><a
                                        href="/channel/info_edit?tab=2&id=<?= $id ?>&p=<?= $p ?>">财务信息</a></li>
                        </ul>
                        <div class="layui-tab-content">
                            <div class="layui-tab-item <?= $tab == 1 ? 'layui-show' : '' ?>">
                                <div class="layui-form" lay-filter="">
                                    <input type="hidden" name="id" value="<?= $info['id'] ?>">
                                    <div class="layui-form-item">
                                        <label class="layui-form-label">渠道账号</label>
                                        <div class="layui-input-inline">
                                            <input type="text" name="" value="<?= $info['username'] ?>" disabled
                                                   class="layui-input">
                                        </div>
                                    </div>
                                    <div class="layui-form-item">
                                        <label class="layui-form-label">渠道密码</label>
                                        <div class="layui-input-inline">
                                            <input type="password" name="password" value="" class="layui-input">
                                        </div>
                                        <div class="layui-form-mid layui-word-aux">(不修改请留空)</div>
                                    </div>
                                    <div class="layui-form-item">
                                        <label class="layui-form-label">确认渠道密码</label>
                                        <div class="layui-input-inline">
                                            <input type="password" name="password1" value="" class="layui-input">
                                        </div>
                                        <div class="layui-form-mid layui-word-aux">(不修改请留空)</div>
                                    </div>
                                    <div class="layui-form-item">
                                        <label class="layui-form-label">渠道类型</label>
                                        <div class="layui-input-block">
                                            <input type="radio" name="type" <?= $info['type'] == 1 ? 'checked' : '' ?>
                                                   value="1" title="可盘官方">
                                            <input type="radio" name="type" <?= $info['type'] == 2 ? 'checked' : '' ?>
                                                   value="2" title="第三方">
                                        </div>
                                    </div>
                                    <div class="layui-form-item">
                                        <label class="layui-form-label">结算方式</label>
                                        <div class="layui-input-inline">
                                            <select name="settlement_type" lay-verify="">
                                                <option value="">请选择结算方式</option>
                                                <option value="1" <?= $info['settlement_type'] == 1 ? 'selected' : '' ?>>CPC</option>
                                                <option value="2" <?= $info['settlement_type'] == 2 ? 'selected' : '' ?>>CPS</option>
                                                <option value="3" <?= $info['settlement_type'] == 3 ? 'selected' : '' ?>>工会</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="layui-form-item">
                                        <label class="layui-form-label">联系人</label>
                                        <div class="layui-input-inline">
                                            <input type="text" name="contact" value="<?= $info['contact'] ?>" placeholder="请输入联系人姓名"
                                                   autocomplete="off" class="layui-input">
                                        </div>
                                        <div class="layui-form-mid layui-word-aux">(选填)</div>
                                    </div>
                                    <div class="layui-form-item">
                                        <label class="layui-form-label">QQ</label>
                                        <div class="layui-input-inline">
                                            <input type="text" name="qq" value="<?= $info['qq'] ?>" placeholder="请输入QQ号"
                                                   autocomplete="off" class="layui-input">
                                        </div>
                                        <div class="layui-form-mid layui-word-aux">(选填)</div>
                                    </div>
                                    <div class="layui-form-item">
                                        <label class="layui-form-label">微信</label>
                                        <div class="layui-input-inline">
                                            <input type="text" name="wechat" value="<?= $info['wechat'] ?>"
                                                   placeholder="请输入微信号"
                                                   lay-verType="tips" autocomplete="off" class="layui-input">
                                        </div>
                                        <div class="layui-form-mid layui-word-aux">(选填)</div>
                                    </div>

                                    <div class="layui-form-item">
                                        <label class="layui-form-label">手机号码</label>
                                        <div class="layui-input-inline">
                                            <input type="text" name="mobile" value="<?= $info['mobile'] ?>"
                                                   placeholder="请输入手机号"
                                                   lay-verify="required"  lay-verType="tips" autocomplete="off" class="layui-input">
                                        </div>
                                        <div class="layui-form-mid layui-word-aux"></div>
                                    </div>

                                    <div class="layui-form-item">
                                        <label class="layui-form-label">备注</label>
                                        <div class="layui-input-inline" style="width: 600px">
                                            <textarea name="remarks" placeholder="请输入备注" class="layui-textarea"><?= $info['remarks'] ?></textarea>
                                        </div>
                                        <div class="layui-form-mid layui-word-aux">(选填)</div>
                                    </div>

                                    <div class="layui-form-item">
                                        <label class="layui-form-label">状态</label>
                                        <div class="layui-input-block">
                                            <input type="radio" name="status"
                                                   value="1" <?= $info['status'] == 1 ? 'checked' : '' ?> title="正常">
                                            <input type="radio" name="status"
                                                   value="0" <?= strlen($info['status']) >= 0 && $info['status'] == 0 ? 'checked' : '' ?>
                                                   title="关闭">
                                        </div>
                                        <div class="layui-form-mid layui-word-aux"></div>
                                    </div>

                                    <div class="layui-form-item">
                                        <label class="layui-form-label">所属商务</label>
                                        <div class="layui-input-inline">
                                            <select name="business_id" lay-verify="">
                                                <option value="">请选择商务</option>
                                                <?php foreach ($business as $v) { ?>
                                                    <option value="<?= $v['id'] ?>" <?= $info['business_id'] == $v['id'] ? 'selected' : '' ?>><?= $v['nickname'] ?></option>
                                                <?php } ?>
                                            </select>
                                        </div>
                                        <div class="layui-form-mid layui-word-aux"></div>
                                    </div>

                                    <div class="layui-form-item">
                                        <div class="layui-input-block">
                                            <button class="layui-btn" lay-submit lay-filter="channel-info-edit">提交
                                            </button>
                                            <a class="layui-btn layui-btn-primary"
                                               href="/channel/index?p=<?= $p ?>">返回</a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="layui-tab-item <?= $tab == 2 ? 'layui-show' : '' ?>">
                                <div class="layui-form" lay-filter="">
                                    <input type="hidden" name="id" value="<?= $info['id'] ?>">
                                    <div class="layui-form-item">
                                        <label class="layui-form-label">财务类型</label>
                                        <div class="layui-input-block">
                                            <input type="radio"
                                                   name="finance_type" <?= $info['finance_type'] == 1 ? 'checked' : '' ?>
                                                   value="1" title="对公">
                                            <input type="radio"
                                                   name="finance_type" <?= $info['finance_type'] == 2 ? 'checked' : '' ?>
                                                   value="2" title="对私">
                                        </div>
                                    </div>

                                    <div class="layui-form-item">
                                        <label class="layui-form-label">收款主体</label>
                                        <div class="layui-input-inline">
                                            <input type="text" name="payee" value="<?= $info['payee'] ?>" placeholder="请输入收款主体"
                                                   lay-verify="required" lay-verType="tips" autocomplete="off" class="layui-input">
                                        </div>
                                    </div>
                                    <div class="layui-form-item">
                                        <label class="layui-form-label">账号</label>
                                        <div class="layui-input-inline">
                                            <input type="text" name="bank_account" id="bank_account" data-val="1" value="<?= $info['bank_account'] ?>" placeholder="请输入账号"
                                                   lay-verify="required" lay-verType="tips" autocomplete="off" class="layui-input bank-account">
                                        </div>
                                    </div>
                                    <div class="layui-form-item">
                                        <label class="layui-form-label">银行</label>
                                        <div class="layui-input-inline">
                                            <input type="text" name="bank" id="bankName" value="<?= $info['bank'] ?>" placeholder="请输入银行名"
                                                   lay-verify="required" lay-verType="tips" autocomplete="off" class="layui-input">
                                        </div>
                                    </div>
                                    <div class="layui-form-item">
                                        <label class="layui-form-label">省份/城市</label>
                                        <div class="layui-input-inline">
                                            <select id="drpprovince" name="bank_province" class="select"
                                                    lay-filter="drpprovince">
                                                <option value="">省份</option>
                                                <?php foreach ($pro as $item) { ?>
                                                    <option value="<?= $item['id'] ?>"  <?= $info['bank_province'] == $item['id'] ? 'selected' : '' ?> ><?= $item['name'] ?></option>
                                                <?php } ?>
                                            </select>
                                        </div>
                                        <div class="layui-input-inline">
                                            <select id="drpcity" name="bank_city" class="select"
                                                    lay-filter="drpcity">
                                                <option value="">城市</option>
                                                <div style="display: none">
                                                    <?php foreach ($city as $item) { ?>
                                                        <option value="<?= $item['id'] ?>" <?= $info['bank_city'] == $item['id'] ? 'selected' : '' ?>><?= $item['name'] ?></option>
                                                    <?php } ?>
                                                </div>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="layui-form-item">
                                        <label class="layui-form-label">分行</label>
                                        <div class="layui-input-inline">
                                            <input type="text" name="bank_branches" value="<?= $info['bank_branches'] ?>" placeholder="请输入分行"
                                                   lay-verify="required" lay-verType="tips" autocomplete="off" class="layui-input">
                                        </div>
                                    </div>

                                    <div class="layui-form-item">
                                        <div class="layui-input-block">
                                            <button class="layui-btn" lay-submit lay-filter="channel-finance_edit">
                                                提交财务信息
                                            </button>
                                            <a class="layui-btn layui-btn-primary" href="/channel/index?p=<?= $p ?>">返回</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
</div>


<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script type="text/javascript" src="/common/js/plupload-2.1.2/js/plupload.full.min.js"></script>
<script type="text/javascript" src="/common/js/oss.upload.lib.js?t=20190402"></script>
<script type="text/javascript" src="/common/js/clipboard.min.js"></script>
<script>
    layui.extend({
        autocomplete: '/layuiadmin/autocomplete/autocomplete'
    }).use(['form', 'layer', 'element', 'autocomplete'], function () {
            var $ = layui.$,
                form = layui.form,
                layer = layui.layer,
                autocomplete = layui.autocomplete;

            // 基本信息提交
            form.on('submit(channel-info-edit)', function (obj) {
                $.ajax({
                    url: '/channel/info_edit',
                    type: "POST",
                    dataType: "JSON",
                    data: obj.field,
                    success: function (resp) {
                        if (resp.code == 200) {
                            layer.msg('编辑基本信息成功', {icon: 1, time: 1000}, function () {
                                location.href = '/channel/index?p=' + <?= $p ?>;
                            });
                        } else {
                            layer.msg(resp.msg, {icon: 5, time: 1000});
                        }
                    }
                })
            });

            // 财务信息提交
            form.on('submit(channel-finance_edit)', function (obj) {
                $.ajax({
                    url: '/channel/finance_edit',
                    type: "POST",
                    dataType: "JSON",
                    data: obj.field,
                    success: function (resp) {
                        if (resp.code == 200) {
                            layer.msg('编辑财务信息成功', {icon: 1, time: 1000}, function () {
                                location.href = '/channel/index?p' + <?= $p ?>;
                            });
                        } else {
                            layer.msg(resp.msg, {icon: 5, time: 1000});
                        }
                    }
                })
            });

            /** 城市联动 开始 **/
            var proid = 0;
            form.on('select(drpprovince)', function (data) {
                var proid = data.value;
                $('#drpcity').html("");
                $.getJSON('/region/get_citys?pid=' + proid, function (data) {
                    $.each(data.data, function (i, item) {
                        $('#drpcity').append('<option  value=' + item.id + '>' + item.name + "</option>");
                    });
                    form.render('select');
                });
            });
            /** 城市联动 结束 **/

        /** 自动获取银行卡信息 开始 **/
        $('.bank-account').on('blur', function () {
            var bank_account = $(this).val();
            var status = $(this).data('val');

            checkBankCardNumber(bank_account, status);
        });

        //银行卡号验证
        function checkBankCardNumber(bankcardnumber, status) {
            //长度校验
            if (bankcardnumber == "" || bankcardnumber.length < 16 || bankcardnumber.length > 19) {
                layer.msg("银行卡号位数必须在16~19之间，请完整输入银行卡号！", {icon: 5, time: 1000});
                return false;
            }

            //开头6位校验
            var strBin = "10,18,30,35,37,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,58,60,62,65,68,69,84,87,88,94,95,98,99";
            if (strBin.indexOf(bankcardnumber.substring(0, 2)) == -1) {
                layer.msg("银行卡号开头6位不符合规范，请检查后重新输入！", {icon: 5, time: 1000});
                return false;
            }

            //全数字校验
            var num = /^\d*$/;
            if (!num.exec(bankcardnumber)) {
                layer.msg("银行卡号必须全为数字，请检查后重新输入！", {icon: 5, time: 1000});
                return false;
            }

            //Luhm验证
            var lastNum = bankcardnumber.substr(bankcardnumber.length - 1, 1);//取出最后一位（与luhm进行比较）
            var first15Num = bankcardnumber.substr(0, bankcardnumber.length - 1);//前15或18位
            var newArr = new Array();
            for (var i = first15Num.length - 1; i > -1; i--) {	//前15或18位倒序存进数组
                newArr.push(first15Num.substr(i, 1));
            }
            var arrJiShu = new Array();					//奇数位*2的积 <9
            var arrJiShu2 = new Array();				//奇数位*2的积 >9
            var arrOuShu = new Array();					//偶数位数组
            for (var j = 0; j < newArr.length; j++) {
                if ((j + 1) % 2 == 1) {							//奇数位
                    if (parseInt(newArr[j]) * 2 < 9)
                        arrJiShu.push(parseInt(newArr[j]) * 2);
                    else
                        arrJiShu2.push(parseInt(newArr[j]) * 2);
                } else									//偶数位
                    arrOuShu.push(newArr[j]);
            }
            var jishu_child1 = new Array();//奇数位*2 >9 的分割之后的数组个位数
            var jishu_child2 = new Array();//奇数位*2 >9 的分割之后的数组十位数
            for (var h = 0; h < arrJiShu2.length; h++) {
                jishu_child1.push(parseInt(arrJiShu2[h]) % 10);
                jishu_child2.push(parseInt(arrJiShu2[h]) / 10);
            }
            var sumJiShu = 0; //奇数位*2 < 9 的数组之和
            var sumOuShu = 0; //偶数位数组之和
            var sumJiShuChild1 = 0; //奇数位*2 >9 的分割之后的数组个位数之和
            var sumJiShuChild2 = 0; //奇数位*2 >9 的分割之后的数组十位数之和
            var sumTotal = 0;
            for (var m = 0; m < arrJiShu.length; m++) {
                sumJiShu = sumJiShu + parseInt(arrJiShu[m]);
            }
            for (var n = 0; n < arrOuShu.length; n++) {
                sumOuShu = sumOuShu + parseInt(arrOuShu[n]);
            }
            for (var p = 0; p < jishu_child1.length; p++) {
                sumJiShuChild1 = sumJiShuChild1 + parseInt(jishu_child1[p]);
                sumJiShuChild2 = sumJiShuChild2 + parseInt(jishu_child2[p]);
            }
            //计算总和
            sumTotal = parseInt(sumJiShu) + parseInt(sumOuShu) + parseInt(sumJiShuChild1) + parseInt(sumJiShuChild2);
            //计算Luhm值
            var k = parseInt(sumTotal) % 10 == 0 ? 10 : parseInt(sumTotal) % 10;
            var luhm = 10 - k;

            if (lastNum != luhm) {
                layer.msg("银行卡号不合法，请检查后重新输入！", {icon: 5, time: 1000});
                return false;
            }
            if (status == 1) {
                $.ajax({
                    type: "post",
                    dataType: "json",
                    url: "/channel/auto_bank_info",
                    data: {bank_account: bankcardnumber},
                    success: function (json) {
                        console.log(json);
                        if (json.code == 200) {
                            $("#bankName").val(json.data.bankName);
                            $("#bank_account").data('val', 0);
                            $("#drpprovince option").each(function () {
                                if ($(this).val() == json.data.bank_province) {
                                    $(this).attr('selected', true)
                                }
                            });
                            $("#drpcity option").each(function () {
                                if ($(this).val() == json.data.bank_city) {
                                    $(this).attr('selected', true)
                                }
                            });
                            $("#drpprovince").next('.layui-unselect').find('input').val(json.data.bank_province_name);
                            $("#drpcity").next('.layui-unselect').find('input').val(json.data.bank_city_name);
                        } else {
                            layer.msg(json.msg, {icon:5, time: 1000});
                        }
                    }
                });
            }
        }

        $('.bank-account').on('change', function () {
            $("#bank_account").data('val', 1);
        });
        /** 自动获取银行卡信息 结束 **/

            //搜索研发商
            $('#developer_name').on('keydown', function (event) {
                if (event.keyCode == 8) {
                    $('input[name="developer_id"]').val('')
                }
            });
            autocomplete.init({
                elem: "#developer_name",
                textLength: 2,//触发长度
                delay: 200,//触发延迟
                callback: {
                    data: function (val, render) {
                        $.ajax({
                            type: "post",
                            dataType: "json",
                            url: "/developer/autocomplete",
                            data: {name: val},
                            success: function (json) {
                                if (json.code == 200) {
                                    render(json.data);
                                } else {
                                    layer.alert(json.msg);
                                }
                            }
                        });
                    },
                    selected: function (data) {
                        $('input[name="developer_id"]').val(data.value)
                    },
                    close: function () {
                    }
                }
            });
        }
    );
</script>
</body>
</html>