<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>
<body>
<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-form layui-card-header layuiadmin-card-header-auto">
            <div class="layui-form-item">
                <form method="get">
                    <div class="layui-col-xs2">
                        <div class="layui-inline">
                            <a class="layui-btn layui-btn-primary" href="/channel/index?p=<?= $p ?>">返回</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="layui-card-body">
            <table class="layui-table layui-form">
                <colgroup>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col width="160">
                </colgroup>
                <thead>
                <tr>
                    <th>子渠道ID</th>
                    <th>子渠道名称</th>
                    <th>创建日期</th>
                    <th>分成</th>
                    <th>状态</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($list as $item) { ?>
                    <tr data-id="<?= $item['id'] ?>">
                        <td><?= $item['id'] ?></td>
                        <td><?= $item['username'] ?></td>
                        <td><?= date('Y-m-d H:i:s', $item['addtime']) ?></td>
                        <td><?= $item['share_ratio'] ?> %</td>
                        <td>
                            <input type="checkbox" value="1" lay-filter="status" name="status" <?= ($item['status'] == 1) ? 'checked' : '' ?> lay-skin="switch" lay-text="开启|关闭">
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            <?= $page ?>
        </div>
    </div>
</div>
<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.extend({
        autocomplete: '/layuiadmin/autocomplete/autocomplete'
    }).use(['form', 'autocomplete'], function () {
        var $ = layui.$
            , form = layui.form
            , autocomplete = layui.autocomplete;

        //启用禁用
        form.on('switch(status)', function (data) {
            var id = $(this).closest('tr').data('id');
            var val = data.elem.checked ? 1 : 0;
            $.ajax({
                type: "post",
                dataType: "json",
                url: "/channel/toggle",
                data: {id: id, field: 'status', val: val},
                success: function (json) {
                    if (json.code == 200) {
                        layer.msg('操作成功', {icon: 1, time: 1000});
                    } else {
                        layer.alert(json.msg);
                    }
                }
            });
        });

    });
</script>
</body>
</html>
