<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>
<body>
<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-form layui-card-header layuiadmin-card-header-auto layui-row">
            <div class="layui-col-xs2">
                <div class="layui-inline"><a class="layui-btn" href="/gift_code/add?id=<?= $giftId ?>">添加兑换码</a></div>
            </div>
            <form method="get">
                <div class="layui-col-xs10 text-right">
                    <input type="hidden" name="id" value="<?= $giftId ?>">
                    <div class="layui-inline">
                        <input type="text" name="code" id="code" value="<?= $code ?>" placeholder="兑换码" autocomplete="off"
                               class="layui-input">
                    </div>
                    <div class="layui-inline">
                        <input type="text" name="user_id" value="<?= $user_id ?>" placeholder="会员ID" autocomplete="off"
                               class="layui-input">
                    </div>
                    <div class="layui-inline text-left">
                        <input type="text" name="imei" value="<?= $imei ?>" placeholder="设备码" autocomplete="off"
                               class="layui-input">
                    </div>
                    <div class="layui-inline" style="width: 150px;">
                        <input type="text" name="start_time" id="start_time" value="<?= $start_time ?>"
                               placeholder="开始日期" autocomplete="off" class="layui-input">
                    </div>
                    <span class="layui-inline">至</span>
                    <div class="layui-inline" style="width: 150px;">
                        <input type="text" name="end_time" id="end_time" value="<?= $end_time ?>"
                               placeholder="结束日期" autocomplete="off" class="layui-input">
                    </div>
                    <div class="layui-inline">
                        <button class="layui-btn layuiadmin-btn-list" type="submit">
                            <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <div class="layui-card-header">
            <div class="layui-col-xs2">
                <div class="layui-inline">
                    <button class="layui-btn" id="del_all">一 键 删 除</button>
                </div>
                <div class="layui-inline">
                    <a class="layui-btn layui-btn-primary" href="/gift/index?p=<?= $last_page ?>">返回</a>
                </div>
            </div>
            <div class="layui-col-xs10 text-right">
                <div class="layui-inline" style="width: 200px">
                    <span>礼包名称：<?= $giftInfo['name'] ?></span>
                </div>
                <div class="layui-inline" style="width: 200px">
                    <span>游戏名称：<?= $gameName ?></span>
                </div>
            </div>
        </div>
        <div class="layui-card-body">
            <table class="layui-table layui-form" id="table_id">
                <colgroup>
                    <col width="40">
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col width="160">
                </colgroup>
                <thead>
                <tr>
                    <th><input type="checkbox" lay-filter="check-all" lay-skin="primary"></th>
                    <th>卡号ID</th>
                    <th>兑换码</th>
                    <th>领取会员ID</th>
                    <th>设备码</th>
                    <th>领取时间</th>
                    <th>是否使用</th>
                    <th>录入时间</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($list as $item) { ?>
                    <tr data-id="<?= $item['id'] ?>">
                        <td><input type="checkbox" name="ids" lay-skin="primary" data-id="<?= $item['id'] ?>"></td>
                        <td><?= $item['id'] ?></td>
                        <td><?= $item['code'] ?></td>
                        <td><?= $item['user_id'] != 0 ? $item['user_id'] : '' ?></td>
                        <td><?= $item['imei'] ?></td>
                        <td><?= $item['receive_time'] != 0 ? date('Y-m-d H:i:s', $item['receive_time']) : '' ?></td>
                        <td><?= $item['used'] == 1 ? '已使用' : '未使用' ?></td>
                        <td><?= date('Y-m-d H:i:s', $item['addtime']) ?></td>
                        <td>
                            <a class="layui-btn layui-btn-xs layui-btn-danger delete">
                                <i class="layui-icon layui-icon-delete"></i>删除
                            </a>
                            <a class="layui-btn layui-btn-xs" href="#">
                                <i class="layui-icon layui-icon-edit"></i>回收
                                <!-- 先放着,需要问产品 -->
                            </a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            <?= $page ?>
        </div>
    </div>
</div>

<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.extend({
        autocomplete: '/layuiadmin/autocomplete/autocomplete'
    }).use(['form', 'laydate', 'table', 'autocomplete'], function () {
        var $ = layui.$,
            laydate = layui.laydate,
            table = layui.table,
            form = layui.form,
            autocomplete = layui.autocomplete;

        // 搜索设备码
        $('#code').on('keydown', function (event) {
            if (event.keyCode == 6) {
                $('input[name="code"]').val('')
            }
        });
        autocomplete.init({
            elem: "#code",
            textLength: 2,//触发长度
            delay: 200,//触发延迟
            callback: {
                data: function (val, render) {
                    $.ajax({
                        type: "post",
                        dataType: "json",
                        url: "/gift_code/autocomplete",
                        data: {name: val},
                        success: function (json) {
                            if (json.code == 200) {
                                render(json.data);
                            } else {
                                layer.alert(json.msg);
                            }
                        }
                    });
                },
                selected: function (data) {
                    console.log(data);
                    $('input[name="code"]').val(data.value)
                },
                close: function () {
                }
            }
        });

        //开始日期
        var insStart = laydate.render({
            elem: '#start_time'
            , done: function (value, date) {
                //更新结束日期的最小日期
                insEnd.config.min = lay.extend({}, date, {
                    month: date.month - 1
                });

                //自动弹出结束日期的选择器
                insEnd.config.elem[0].focus();
            }
        });

        //结束日期
        var insEnd = laydate.render({
            elem: '#end_time'
            , done: function (value, date) {
                //更新开始日期的最大日期
                insStart.config.max = lay.extend({}, date, {
                    month: date.month - 1
                });
            }
        });

        function batchdel(ids, callback) {
            $.ajax({
                type: "post",
                dataType: "json",
                url: "/gift_code/delete",
                data: {"ids": ids},
                success: function (json) {
                    if (json.code == 200) {
                        layer.msg('删除成功', {icon: 1, time: 1000}, function () {
                            if (typeof callback == 'function') callback();
                        });
                    } else {
                        layer.alert(json.msg)
                    }
                }
            })
        }

        //单个删除
        $('.delete').on('click', function () {
            var ids = [];
            var tr = $(this).closest('tr');
            ids.push(tr.data('id'));
            layer.confirm('确定要删除吗？', {btn: ['确定', '取消']}, function () {
                batchdel(ids, function () {
                    tr.remove();
                });
            });
        });

        //全选
        form.on('checkbox(check-all)', function (data) {
            $('input[name="ids"]').prop("checked", data.elem.checked);
            form.render('checkbox');
        });

        //批量删除
        $('#del_all').on('click', function () {
            var ids = [];
            $('input[name="ids"]:checked').each(function () {
                ids.push($(this).data('id'))
            })
            if (ids.length <= 0) {
                layer.msg('请先选择兑换码', {icon: 5, time:1000});
                return false;
            }
            layer.confirm('确定要删除吗？', {btn: ['确定', '取消']}, function () {
                batchdel(ids, function () {
                    window.location.reload();
                });
            });

        });

    });
</script>
</body>
</html>
