<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
    <style>.overflow{white-space: nowrap;text-overflow: ellipsis;overflow: hidden;word-break: break-all;}</style>
</head>
<body>
<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-form layui-card-header layuiadmin-card-header-auto layui-row">
            <form method="get">
                <div class="layui-col-xs2">
                    <div class="layui-inline"><a class="layui-btn" href="/ad/add">添加</a></div>
                </div>
                <div class="layui-col-xs10 text-right">
                    <div class="layui-inline">
                        <input type="text" name="name" value="<?=$name?>" placeholder="广告简称" autocomplete="off" class="layui-input">
                    </div>
                    <div class="layui-inline text-left" style="width: 120px;">
                        <select name="ownerid">
                            <option value="">广告主</option>
                            <?php foreach ($list_adowner as $adowner) {?>
                                <option value="<?=$adowner['id']?>" <?php if($ownerid == $adowner['id']){echo 'selected';}?>><?=$adowner['name']?></option>
                            <?php }?>
                        </select>
                    </div>
                    <div class="layui-inline text-left" style="width: 120px;">
                        <select name="zoneid">
                            <option value="">广告位</option>
                            <?php foreach ($list_adzone as $adzone) {?>
                                <option value="<?=$adzone['id']?>" <?php if($zoneid == $adzone['id']){echo 'selected';}?>><?=$adzone['title']?></option>
                            <?php }?>
                        </select>
                    </div>
                    <div class="layui-inline text-left" style="width: 120px;">
                        <select name="platform">
                            <option value="">平台</option>
                            <option value="1" <?php if($platform == 1){echo 'selected';}?>>安卓</option>
                            <option value="2" <?php if($platform == 2){echo 'selected';}?>>iOS</option>
                        </select>
                    </div>
                    <div class="layui-inline text-left" style="width: 120px;">
                        <select name="status">
                            <option value="">状态</option>
                            <option value="0" <?php if(!$status && strlen(trim($status))){echo 'selected';}?>>停用</option>
                            <option value="1" <?php if($status == 1){echo 'selected';}?>>展现</option>
                        </select>
                    </div>
                    <div class="layui-inline">
                        <input type="text" name="startdate" id="startdate" value="<?=$startdate?>" placeholder="开始日期" autocomplete="off" class="layui-input">
                    </div>
                    <div class="layui-inline">
                        <input type="text" name="enddate" id="enddate" value="<?=$enddate?>" placeholder="结束日期" autocomplete="off" class="layui-input">
                    </div>
                    <div class="layui-inline">
                        <button class="layui-btn layuiadmin-btn-list" type="submit">
                            <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>

        <div class="layui-row highlight-block">
            <div class="layui-col-md12">
                展示广告数：<span><?=$summary['total']?></span>
                展现量：<span><?=$summary['total_display']?></span>
                点击数：<span><?=$summary['total_click']?></span>
                点击率：<span><?php if($summary['total_display']){ echo (sprintf("%.2f",$summary['total_click']/$summary['total_display']*100)).'%';} else {echo '0';} ?></span>
            </div>
        </div>

        <div class="layui-card-body">
            <table class="layui-table layui-form">
                <colgroup>
                    <col width="60">
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col width="150">
                    <col>
                    <col>
                    <col>
                    <col>
                    <col width="100">
                    <col width="190">
                </colgroup>
                <thead>
                <tr>
                    <th>编号</th>
                    <th>平台</th>
                    <th>广告简称</th>
                    <th>广告位置</th>
                    <th>广告主</th>
                    <th>广告标题</th>
                    <th>点击动作</th>
                    <th>有效期</th>
                    <th>展示量</th>
                    <th>点击量</th>
                    <th>点击率</th>
                    <th>权重</th>
                    <th>状态</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($list as $item){?>
                    <tr data-id="<?=$item['id']?>">
                        <td><?=$item['id']?></td>
                        <!--<td><input type="text" name="sort" class="table-text sort" style="width: 40px;" data-val="<?/*=$item['sort'];*/?>" value="<?/*=$item['sort'];*/?>"></td>-->
                        <td><?php if($item['platform'] ==2){echo 'iOS';}else{echo '安卓';}?></td>
                        <td><?=$item['name']?></td>
                        <td><?=$item['adzone_name']?></td>
                        <td><?=$item['owner']?></td>
                        <td class="overflow"><a class="tip-img" style="color: #009688" href="javascript:void(0);" data-img="<?=$item['img']?>">【素材图】</a><?=$item['title']?></td>
                        <td style="word-break:break-all">
                            <?php switch ($item['ad_type']) {
                                case 1:
                                    echo sprintf('<a target="_blank" href="%s" title="%s" style="color:#009688;">下载包</a>', $item['link'], $item['link']);
                                    break;
                                case 2:
                                    echo sprintf('<a target="_blank" href="%s" title="%s" style="color:#009688;">H5链接</a>', $item['link'], $item['link']);
                                    break;
                                case 3:
                                    $parse_url = parse_url($item['link']);
                                    $key = sprintf('%s://%s%s', $parse_url['scheme'], $parse_url['host'], $parse_url['path']);
                                    echo $app_intents[$key]['title'] ?? '';
                                    break;
                            }?>
                        </td>
                        <td>开始：<?=$item['start_time']?><br>结束：<?=$item['end_time']?></td>
                        <td><?=$item['display'];?></td>
                        <td><?=$item['click'];?></td>
                        <td><?php if($item['display']){ echo (sprintf("%.2f",$item['click']/$item['display']*100)).'%';} else {echo '0';} ?></td>
                        <td><?=$item['weight'];?></td>
                        <td><input type="checkbox" value="1" lay-filter="status" name="status" <?=($item['status'] == 1) ? 'checked' : ''?> lay-skin="switch" lay-text="启用|禁用"></td>
                        <td>
                            <div class="layui-btn-group">
                                <a class="layui-btn layui-btn-sm" title="编辑" href="/ad/edit?id=<?=$item['id']?>&p=<?= $p ?>"><i class="layui-icon">&#xe642;</i></a>
                                <a class="layui-btn layui-btn-sm delete" title="删除"><i class="layui-icon">&#xe640;</i></a>
                                <a class="layui-btn layui-btn-sm copy" title="复制" data-id="<?=$item['id']?>"><i class="layui-icon">&#xe621;</i></a>
                                <a class="layui-btn layui-btn-sm" title="报表" href="/ad/stat?ad_id=<?=$item['id']?>&startdate=<?=$startdate?>&enddate=<?=$enddate?>&type=2&p=<?= $p ?>"><i class="layui-icon">&#xe62d;</i></a>
                            </div>
                        </td>
                    </tr>
                <?php }?>
                </tbody>
            </table>
            <?=$page?>
        </div>
    </div>
</div>

<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.use(['form', 'laydate'], function(){
        var $ = layui.$
            ,form = layui.form
            ,layer = layui.layer
            ,laydate = layui.laydate;

        //启用禁用
        form.on('switch(status)', function (data) {
            console.log(data.elem.checked);
            var id = $(this).closest('tr').data('id');
            var status = data.elem.checked ? 1 : 0;
            $.ajax({
                type: "post",
                dataType: "json",
                url: "/ad/toggle",
                data: {id: id, field: 'status', val: status},
                success: function (json) {
                    if (json.code == 200) {
                        layer.msg('操作成功');
                    } else {
                        layer.alert(json.msg);
                    }
                }
            });
        });

        //修改排序
        $('.sort').on('blur', function () {
            var id = $(this).closest('tr').data('id');
            var oldval = parseInt($(this).data('val'));
            var sort = parseInt($(this).val());
            var self = $(this);
            if (sort >= 0 && oldval != sort) {
                $.ajax({
                    type: "POST",
                    dataType: "JSON",
                    url: '/ad/update_sort',
                    data: {"id": id, "sort": sort},
                    success: function (json) {
                        if (json.code == 200) {
                            self.data('val', sort);
                            layer.msg('操作成功', {time: 800});
                        } else {
                            layer.alert(json.msg)
                        }
                    }
                })
            }
        });

        var ajaxDelete = function(ids, callback) {
            $.ajax({
                type: "post",
                dataType: "json",
                url: "/ad/delete",
                data: {"ids": ids},
                success: function (json) {
                    if (json.code == 200) {
                        layer.msg('删除成功', {icon: 1, time: 1000}, function () {
                            if (typeof callback == 'function') {
                                callback();
                            }
                        });
                    } else {
                        layer.alert(json.msg)
                    }
                }
            })
        }

        //单个删除
        $('.delete').on('click', function () {
            var ids = [];
            var tr = $(this).closest('tr');
            ids.push(tr.data('id'));
            layer.confirm('确定要删除吗？', {btn:['确定', '取消']}, function () {
                ajaxDelete(ids, function () {
                    tr.remove();
                });
            });
        });

        //开始日期
        var insStart = laydate.render({
            elem: '#startdate'
            ,done: function(value, date){
                //更新结束日期的最小日期
                insEnd.config.min = lay.extend({}, date, {
                    month: date.month - 1
                });

                //自动弹出结束日期的选择器
                insEnd.config.elem[0].focus();
            }
        });

        //结束日期
        var insEnd = laydate.render({
            elem: '#enddate'
            ,done: function(value, date){
                //更新开始日期的最大日期
                insStart.config.max = lay.extend({}, date, {
                    month: date.month - 1
                });
            }
        });

        //复制功能
        $('.copy').on('click', function () {
            var id = $(this).data('id');
            layer.confirm('确定要复制吗？', {btn:['确定', '取消']}, function () {
                ajaxCopy(id);
            });


        });

        var ajaxCopy = function (id) {
            $.get('/ad/copy', {id: id}, function (json) {
                if (json.code != 200) {
                    layer.alert(json.msg);
                    return false;
                }
                layer.msg('复制成功', {time: 800});
                setInterval(function () {
                    location.reload();
                }, 800);
            }, 'json')
        }

        //鼠标滑过显示图片
        var tip = null; // tips提示
        $('.tip-img').hover(function(){
            var img = "<img src='"+$(this).data('img')+"' style='max-height:150px;' />";
            tip = layer.tips(img, this, {tips: [2, '#FFF'], area: ['auto', '166px']});
        },function(){
            layer.close(tip);
        });
    });
</script>
</body>
</html>
