<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>
<body>
<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-form layui-card-header layuiadmin-card-header-auto">
            <div class="layui-form-item">
                <div class="layui-col-xs2">
                    <div class="layui-inline">
                        <a class="layui-btn layui-btn-primary" href="/ad/index?p=<?= $p ?>">返回</a>
                    </div>
                </div>
                <div style="float: right">
                    <form method="get">
                        <input type="hidden" name="ad_id" value="<?= $ad_id ?>">
                        <div class="layui-inline" style="width: 120px;">
                            <?php if ($ad_id) { ?>
                                <input type="text" class="layui-input"
                                       value="<?= $list_adowner[$ad_one_info['owner_id']]['name'] ?>" disabled>
                            <?php } else { ?>
                                <select id="ownerid" name="ownerid">
                                    <option value="">广告主</option>
                                    <?php foreach ($list_adowner as $row) { ?>
                                        <?php if ($row['status'] == 1) { ?>
                                            <option value="<?php echo $row['id']; ?>" <?php if ($ownerid == $row['id']) {
                                                echo "selected='selected'";
                                            } ?>><?php echo $row['name']; ?></option>
                                        <?php } ?>
                                    <?php } ?>
                                </select>
                            <?php } ?>
                        </div>
                        <div class="layui-inline" style="width: 120px;">
                            <?php if ($ad_id) { ?>
                                <input type="text" class="layui-input"
                                       value="<?= $list_adzone[$ad_one_info['zoneid']]['title'] ?>" disabled>
                            <?php } else { ?>
                                <select id="zoneid" name="zoneid">
                                    <option value="">广告位</option>
                                    <?php foreach ($list_adzone as $row) { ?>
                                        <?php if ($row['status'] == 1) { ?>
                                            <option value="<?php echo $row['id']; ?>" <?php if ($zoneid == $row['id']) {
                                                echo "selected='selected'";
                                            } ?>><?php echo $row['title']; ?></option>
                                        <?php } ?>
                                    <?php } ?>
                                </select>
                            <?php } ?>
                        </div>
                        <div class="layui-inline" style="width: 120px;">
                            <?php if ($ad_id) { ?>
                                <input type="text" class="layui-input"
                                       value="<?php echo $ad_one_info['platform'] == 1 ? '安卓' : 'IOS'; ?>" disabled="disabled">
                            <?php } else { ?>
                                <select id="platform" name="platform">
                                    <option value="">平台</option>
                                    <option value="1" <?= $platform == '1' ? 'selected="selected"' : ''; ?> >安卓</option>
                                    <option value="2" <?= $platform == '2' ? 'selected="selected"' : ''; ?> >IOS</option>
                                </select>
                            <?php } ?>
                        </div>
                        <div class="layui-inline">
                            <input type="text" name="startdate" id="startdate" value="<?= $startdate ?>" placeholder="开始日期"
                                   autocomplete="off" class="layui-input">
                        </div>
                        <div class="layui-inline">
                            <input type="text" name="enddate" id="enddate" value="<?= $enddate ?>" placeholder="结束日期"
                                   autocomplete="off" class="layui-input">
                        </div>
                        <div class="layui-inline" style="width: 120px;">
                            <?php if ($ad_id) { ?>
                                <input type="text" class="layui-input" value="按日期显示" disabled>
                                <input type="hidden" name="type" value="2">
                            <?php } else { ?>
                                <select class="form-control" name="type">
                                    <option value="1" <?= $type == 1 ? 'selected' : ''; ?>>汇总显示</option>
                                    <option value="2" <?= $type == 2 ? 'selected' : ''; ?>>按日期显示</option>
                                </select>
                            <?php } ?>
                        </div>
                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-list" type="submit">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </form>
                </div>

            </div>

        </div>

        <div class="layui-row highlight-block">
            <div class="layui-col-md12">
                显示广告数: <span><?= $ad_total; ?></span>
                曝光数: <span><?= $total_display; ?></span>
                点击数: <span><?= $total_click; ?></span>
                点击率: <span><?php if ($total_display) {
                        echo (sprintf("%.2f", $total_click / $total_display * 100)) . '%';
                    } else {
                        echo '0';
                    } ?></span>
            </div>
        </div>

        <div class="layui-card-body">
            <table class="layui-table layui-form">
                <colgroup>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col width="100">
                </colgroup>
                <thead>
                <tr>
                    <th>日期</th>
                    <th>广告简称</th>
                    <th>平台</th>
                    <th>广告位置</th>
                    <th>所属广告主</th>
                    <th>当前状态</th>
                    <th>曝光量</th>
                    <th>点击量</th>
                    <th>点击率</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($list as $row) { ?>
                    <tr data-id="<?php echo $row['id']; ?>">
                        <td><?= ($type == 1) ? '--' : $row['date']; ?></td>
                        <td><?= $ad_nature[$row['ad_id']]['name'] ?></td>
                        <td><?php if ($ad_nature[$row['ad_id']]['platform'] == 1) {
                                echo '安卓';
                            } else {
                                echo 'IOS';
                            } ?></td>
                        <td><?php echo $list_adzone[$ad_nature[$row['ad_id']]['zoneid']]['title'] ?? ''; ?></td>
                        <td><?php echo $list_adowner[$ad_nature[$row['ad_id']]['owner_id']]['name'] ?? ''; ?></td>
                        <td><?php if ($row['status'] == 1) {
                                echo "<span style='#009688;'>正常</span>";
                            } elseif ($row['status'] == 2) {
                                echo "<span style='color: red;'>过期</span>";
                            } else {
                                echo "<span style='color: yellow;'>停用</span>";
                            } ?></td>
                        <td><?= $row['display'] ?></td>
                        <td><?= $row['click'] ?></td>
                        <td><?php if ($row['display']) {
                                echo (sprintf("%.2f", $row['click'] / $row['display'] * 100)) . '%';
                            } else {
                                echo '0';
                            } ?></td>
                        <td>
                            <?php if ($type == 1) { ?>
                                <a class="layui-btn layui-btn-xs"
                                   href="/ad/stat?ad_id=<?= $row['ad_id'] ?>&startdate=<?= $startdate ?: date('Y-m-d'); ?>&enddate=<?= $enddate ?: date('Y-m-d'); ?>&type=2">详细报表</a>
                            <?php } ?>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            <?= $page ?>
        </div>
    </div>
</div>

<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.use(['form', 'laydate'], function () {
        var $ = layui.$
            , form = layui.form
            , laydate = layui.laydate;

        //开始日期
        var insStart = laydate.render({
            elem: '#startdate'
            , done: function (value, date) {
                //更新结束日期的最小日期
                insEnd.config.min = lay.extend({}, date, {
                    month: date.month - 1
                });

                //自动弹出结束日期的选择器
                insEnd.config.elem[0].focus();
            }
        });

        //结束日期
        var insEnd = laydate.render({
            elem: '#enddate'
            , done: function (value, date) {
                //更新开始日期的最大日期
                insStart.config.max = lay.extend({}, date, {
                    month: date.month - 1
                });
            }
        });
    });
</script>
</body>
</html>