<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>
<body>

<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">推送调试</div>
                <div class="layui-card-body" pad15>

                    <div class="layui-form" lay-filter="">
                        <div class="layui-form-item">
                            <label class="layui-form-label">用户ID</label>
                            <div class="layui-input-inline">
                                <input type="text" name="user_id" value="" lay-verify="required" lay-tips="tips"  autocomplete="off" class="layui-input">
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">游戏ID</label>
                            <div class="layui-input-inline">
                                <input type="text" name="id" value="" lay-verify="required" lay-tips="tips" autocomplete="off" class="layui-input">
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">H5地址</label>
                            <div class="layui-input-inline">
                                <input type="text" name="url" value="" lay-verify="url" lay-tips="tips" autocomplete="off" class="layui-input">
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">推送内容</label>
                            <div class="layui-input-block">
                                <textarea name="content" class="layui-textarea">测试推送</textarea>
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <button class="layui-btn" lay-submit lay-filter="push-test" data-intent="nop">无动作</button>
                                <button class="layui-btn" lay-submit lay-filter="push-test" data-intent="openapp">启动APP</button>
                                <button class="layui-btn" lay-submit lay-filter="push-test" data-intent="login">跳登陆</button>
                                <button class="layui-btn" lay-submit lay-filter="push-test" data-intent="invite">邀请好友</button>
                                <button class="layui-btn" lay-submit lay-filter="push-test" data-intent="income">收入明细</button>
                                <button class="layui-btn" lay-submit lay-filter="push-test" data-intent="expense">支出明细</button>
                                <button class="layui-btn" lay-submit lay-filter="push-test" data-intent="game">游戏详情</button>
                                <button class="layui-btn" lay-submit lay-filter="push-test" data-intent="userprofile">个人资料</button>
                                <button class="layui-btn" lay-submit lay-filter="push-test" data-intent="webview">打开网页</button>
                                <button class="layui-btn" lay-submit lay-filter="push-test" data-intent="rebate">申请返利</button>
                                <button class="layui-btn" lay-submit lay-filter="push-test" data-intent="rebate_record">返利申请记录</button>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <button class="layui-btn" lay-submit lay-filter="push-test" data-intent="verify_realname">实名认证</button>
                                <button class="layui-btn" lay-submit lay-filter="push-test" data-intent="modify_mobile">修改手机号</button>
                                <button class="layui-btn" lay-submit lay-filter="push-test" data-intent="modify_passwd">修改密码</button>
                                <button class="layui-btn" lay-submit lay-filter="push-test" data-intent="recharge">充值</button>
                                <button class="layui-btn" lay-submit lay-filter="push-test" data-intent="customer_service">联系客服</button>
                                <button class="layui-btn" lay-submit lay-filter="push-test" data-intent="coupon">代金券</button>
                                <button class="layui-btn" lay-submit lay-filter="push-test" data-intent="gifts">礼包</button>
                                <button class="layui-btn" lay-submit lay-filter="push-test" data-intent="message">消息中心</button>
                                <button class="layui-btn" lay-submit lay-filter="push-test" data-intent="feedback">意见反馈</button>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <button class="layui-btn" lay-submit lay-filter="push-test" data-intent="broadcast">全体推送</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.use('form', function () {
        var $ = layui.$
            , form = layui.form
            , layer = layui.layer;

        /*form.verify({
            nickname: [/^[\S]{2,16}$/, '昵称最少2个字符'],
        })*/

        form.on('submit(push-test)', function (obj) {
            var fields = obj.field;
            fields.intent = obj.elem.getAttribute('data-intent');
            $.ajax({
                url: '/push/test',
                type: "POST",
                dataType: "JSON",
                data: fields,
                success: function (resp) {
                    if (resp.code == 200) {
                        layer.msg('提交成功');
                    } else {
                        layer.msg(resp.msg, {icon: 5, time: 1000});
                    }
                }
            })
        })
    });
</script>
</body>
</html>