<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>
<body>

<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">添加菜单</div>
                <div class="layui-card-body" pad15>

                    <div class="layui-form">
                        <div class="layui-form-item">
                            <label class="layui-form-label">父级菜单</label>
                            <div class="layui-input-inline">
                                <select name="pid" id="pid" lay-filter="pid" lay-verify="required" lay-verType="tips">
                                    <option value="0">-- 无 --</option>
                                    <?php foreach ($topMenus as $menu){?>
                                        <option value="<?=$menu['id']?>" <?php if(isset($info['pid']) && $info['pid'] == $menu['id']) {echo 'selected';}?>><?=$menu['title']?></option>
                                    <?php }?>
                                </select>
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">菜单名称</label>
                            <div class="layui-input-inline">
                                <input type="text" name="title" value="<?=$info['title'] ?? '';?>" lay-verify="required" lay-verType="tips"  autocomplete="off" class="layui-input">
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item item-url" style="display: none;">
                            <label class="layui-form-label">菜单链接</label>
                            <div class="layui-input-inline">
                                <input type="text" name="url" value="<?=$info['url'] ?? '';?>" placeholder="如：user/add" autocomplete="off" class="layui-input">
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">状态</label>
                            <div class="layui-input-inline">
                                <input type="hidden" name="display" value="0">
                                <input type="checkbox" value="1" <?php if(isset($info['display']) && $info['display'] ==1) {echo 'checked';}?> name="display" lay-skin="switch" lay-text="显示|隐藏">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <input type="hidden" name="id" value="<?=$info['id'] ?? 0;?>">
                                <button class="layui-btn" lay-submit lay-filter="menu-add">提交</button>
                                <a class="layui-btn layui-btn-primary" href="javascript:void(0);" onclick="history.go(-1)">返回</a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.use('form', function () {
        var $ = layui.$
            , form = layui.form
            , layer = layui.layer;

        /*form.verify({
            nickname: [/^[\S]{2,16}$/, '昵称最少2个字符'],
        })*/

        //显示隐藏
        form.on('select(pid)', function (data) {
            console.log(data)
            pid = parseInt(data.value);
            if (pid > 0) {
                $('.item-url').show();
            } else {
                $('.item-url').hide();
            }
        });

        //自动触发
        $('.layui-form-select dl dd.layui-this').trigger('click');

        //提交表单
        form.on('submit(menu-add)', function (obj) {
            $.ajax({
                url: '/menu/add',
                type: "POST",
                dataType: "JSON",
                data: obj.field,
                success: function (resp) {
                    if (resp.code == 200) {
                        layer.msg('操作成功', {icon: 1, time: 1000}, function () {
                            location.href = '/menu/index';
                        });
                    } else {
                        layer.msg(resp.msg, {icon: 5, time: 1000});
                    }
                }
            })
        })
    });
</script>
</body>
</html>