<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>
<body>
<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-card-body">
            <div style="padding-bottom: 10px;">
                <a class="layui-btn" href="/menu/add">添加</a>
            </div>
            <table class="layui-table layui-form">
                <colgroup>
                    <col width="200">
                    <col width="160">
                    <col width="160">
                    <col>
                    <col width="100">
                    <col width="150">
                </colgroup>
                <thead>
                <tr>
                    <th>菜单名称</th>
                    <th>一级菜单排序</th>
                    <th>二级菜单排序</th>
                    <th>地址</th>
                    <th>状态</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($list as $item){?>
                    <tr data-id="<?=$item['id']?>">
                        <td><i class="layui-icon expand layui-icon-triangle-d"></i> <?=$item['title']?></td>
                        <td><input type="text" class="table-text sort" data-val="<?=$item['sort']?>" value="<?=$item['sort']?>"></td>
                        <td></td>
                        <td></td>
                        <td><input type="checkbox" value="1" lay-filter="display" name="display" <?=($item['display'] == 1) ? 'checked' : ''?> lay-skin="switch" lay-text="显示|隐藏"></td>
                        <td>
                            <a class="layui-btn layui-btn-xs" href="/menu/add?id=<?=$item['id']?>"><i class="layui-icon layui-icon-edit"></i>编辑</a>
                            <a class="layui-btn layui-btn-danger layui-btn-xs delete"><i class="layui-icon layui-icon-delete"></i>删除</a>
                        </td>
                    </tr>
                    <?php if(!empty($item['child'])){foreach($item['child'] as $child){?>
                        <tr class="child-<?=$item['id']?>" data-id="<?=$child['id']?>" style="display: none;">
                            <td>　|--<?=$child['title']?></td>
                            <td></td>
                            <td><input type="text" class="table-text sort" data-val="<?=$child['sort']?>" value="<?=$child['sort']?>"></td>
                            <td><?=$child['url']?></td>
                            <td><input type="checkbox" value="1" lay-filter="display" name="display" <?=($child['display'] == 1) ? 'checked' : ''?> lay-skin="switch" lay-text="显示|隐藏"></td>
                            <td>
                                <a class="layui-btn layui-btn-xs" href="/menu/add?id=<?=$child['id']?>"><i class="layui-icon layui-icon-edit"></i>编辑</a>
                                <a class="layui-btn layui-btn-danger layui-btn-xs delete"><i class="layui-icon layui-icon-delete"></i>删除</a>
                            </td>
                        </tr>
                    <?php }}?>
                <?php }?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.use('form', function () {
        var $ = layui.$
            , form = layui.form;
        
        //展开折叠
        $('.expand').on('click', function () {
            var pid = $(this).closest('tr').data('id');
            if ($(this).hasClass('layui-icon-triangle-d')) {
                $(this).removeClass('layui-icon-triangle-d').addClass('layui-icon-triangle-r');
                $('.child-' + pid).show();
            } else {
                $(this).removeClass('layui-icon-triangle-r').addClass('layui-icon-triangle-d');
                $('.child-' + pid).hide();
            }
        });

        //修改排序
        $('.sort').on('blur', function () {
            var id = $(this).closest('tr').data('id');
            var oldval = parseInt($(this).data('val'));
            var sort = parseInt($(this).val());
            var self = $(this);
            if (sort >= 0 && oldval != sort) {
                $.ajax({
                    type: "POST",
                    dataType: "JSON",
                    url: '/menu/update_sort',
                    data: {"id": id, "sort": sort},
                    success: function (json) {
                        if (json.code == 200) {
                            self.data('val', sort);
                            layer.msg('操作成功', {time: 800});
                        } else {
                            layer.alert(json.msg)
                        }
                    }
                })
            }
        });

        //单个删除
        $('.delete').on('click', function () {
            var tr = $(this).closest('tr');
            var id = tr.data('id');
            layer.confirm('确定要删除吗？', {btn:['确定', '取消']}, function () {
                $.ajax({
                    type: "post",
                    dataType: "json",
                    url: "/menu/delete",
                    data: {"id": id},
                    success: function (json) {
                        if (json.code == 200) {
                            layer.msg('删除成功', {icon: 1, time: 1000}, function () {
                                tr.remove();
                            });
                        } else {
                            layer.alert(json.msg);
                        }
                    }
                });
            })
        });

        //启用禁用
        form.on('switch(display)', function (data) {
            console.log(data.elem.checked)
            var id = $(this).closest('tr').data('id');
            var display = data.elem.checked ? 1 : 0;
            $.ajax({
                type: "post",
                dataType: "json",
                url: "/menu/toggle",
                data: {id: id, display: display},
                success: function (json) {
                    if (json.code == 200) {
                        layer.msg('操作成功');
                    } else {
                        layer.alert(json.msg);
                    }
                }
            });
        });
    });
</script>
</body>
</html>