<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>
<body>
<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-form layui-card-header layuiadmin-card-header-auto">
            <div class="layui-form-item">
                <form method="get">
                    <div style="float: right">
                        <div class="layui-inline">
                            <input type="text" name="id" value="<?= $id > 0 ? $id : '' ?>" class="layui-input" placeholder="小号ID" autocomplete="off">
                        </div>
                        <div class="layui-inline">
                            <input type="text" id="name" value="<?= $name ?>" class="layui-input" placeholder="小号名" autocomplete="off">
                        </div>
                        <div class="layui-inline">
                            <input type="text" name="user_id" value="<?= $user_id > 0 ? $user_id : '' ?>" class="layui-input" placeholder="会员ID" autocomplete="off">
                        </div>
                        <div class="layui-inline">
                            <input type="text" id="user_name" value="<?= $user_name ?>" class="layui-input" placeholder="会员名" autocomplete="off">
                        </div>
                        <div class="layui-inline" style="height: 44px">
                            <button class="layui-btn layuiadmin-btn-list" type="submit">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="layui-card-body">
            <table class="layui-table layui-form">
                <colgroup>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col width="240">
                    <col width="80">
                </colgroup>
                <thead>
                <tr>
                    <th>小号ID</th>
                    <th>小号名称</th>
                    <th>会员ID</th>
                    <th>会员名</th>
                    <th>游戏名称</th>
                    <th>充值金额</th>
                    <th>新增时间</th>
                    <th>锁定</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($list as $item) { ?>
                    <tr data-id="<?= $item['id'] ?>">
                        <td><?= $item['id'] ?></td>
                        <td><?= $item['name'] ?></td>
                        <td><?= $item['user_id'] ?></td>
                        <td><?= $userInfos[$item['user_id']]['username'] ?></td>
                        <td><?= $gameInfos[$item['game_id']]['name'] ?></td>
                        <td><?= $item['total_charge'] ?></td>
                        <td><?= date('Y-m-d H:i:s', $item['addtime']) ?></td>
                        <td>
                            <input type="checkbox" value="" lay-filter="status" name="status"
                                <?= ($item['status'] == 0) ? 'checked' : '' ?> lay-skin="switch" lay-text="是|否">
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            <?= $page ?>
        </div>
    </div>
</div>

<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.extend({
        autocomplete: '/layuiadmin/autocomplete/autocomplete'
    }).use(['form', 'autocomplete'], function () {
        var $ = layui.$
            , form = layui.form
            , autocomplete = layui.autocomplete;

        // 状态修改
        form.on('switch(status)', function (data) {
            var id = $(this).closest('tr').data('id');
            var val = data.elem.checked ? 0 : 1;
            $.ajax({
                type: "post",
                dataType: "json",
                url: "/user_account/toggle",
                data: {id: id, field: "status", val: val},
                success: function (json) {
                    if (json.code == 200) {
                        layer.msg('操作成功', {icon: 1, time: 1000});
                    } else {
                        layer.alert(json.msg);
                    }
                }
            });
        });

        // 搜索会员
        $('#user_name').on('keydown', function (event) {
            if (event.keyCode == 8) {
                $('input[name="user_id"]').val('')
            }
        });
        autocomplete.init({
            elem: "#user_name",
            textLength: 2,//触发长度
            delay: 200,//触发延迟
            callback: {
                data: function (val, render) {
                    $.ajax({
                        type: "post",
                        dataType: "json",
                        url: "/user/autocomplete",
                        data: {name: val},
                        success: function (json) {
                            if (json.code == 200) {
                                render(json.data);
                            } else {
                                layer.alert(json.msg);
                            }
                        }
                    });
                },
                selected: function (data) {
                    console.log(data);
                    $('input[name="user_id"]').val(data.value)
                },
                close: function () {
                }
            }
        });

        // 搜索小号
        $('#name').on('keydown', function (event) {
            if (event.keyCode == 8) {
                $('input[name="id"]').val('')
            }
        });
        autocomplete.init({
            elem: "#name",
            textLength: 2,//触发长度
            delay: 200,//触发延迟
            callback: {
                data: function (val, render) {
                    $.ajax({
                        type: "post",
                        dataType: "json",
                        url: "/user_account/autocomplete",
                        data: {name: val},
                        success: function (json) {
                            if (json.code == 200) {
                                render(json.data);
                            } else {
                                layer.alert(json.msg);
                            }
                        }
                    });
                },
                selected: function (data) {
                    console.log(data);
                    $('input[name="id"]').val(data.value)
                },
                close: function () {
                }
            }
        });
    });
</script>
</body>
</html>
