<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>
<body>
<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-form layui-card-header layuiadmin-card-header-auto layui-row">
            <div class="layui-form-item">
                <form method="get">
                    <div class="layui-col-xs2">
                        <div class="layui-inline"><a class="layui-btn" href="/activity/add">添加活动</a></div>
                    </div>
                    <div class="layui-col-xs10 text-right">
                        <div class="layui-inline">
                            <input type="hidden" name="activity_id" value="<?= $activity_id ?>">
                            <input type="text" name="activity_name" id="activity_name" value="<?= $activity_name ?>"
                                   class="layui-input"
                                   placeholder="输入活动的名称" autocomplete="off">
                        </div>
                        <div class="layui-inline">
                            <input type="hidden" name="game_id" value="<?= $game_id ?>">
                            <input type="text" name="game_name" id="game_name" value="<?= $game_name ?>"
                                   class="layui-input" placeholder="游戏名称" autocomplete="off">
                        </div>
                        <div class="layui-inline text-left" style="width: 120px;">
                            <select name="type">
                                <option value="">选择活动类型</option>
                                <option value="1" <?= $type == 1 ? 'selected' : '' ?>>活动公告</option>
                                <option value="2" <?= $type == 2 ? 'selected' : '' ?>>独家活动</option>
                                <option value="3" <?= $type == 3 ? 'selected' : '' ?>>游戏攻略</option>
                            </select>
                        </div>
                        <div class="layui-inline text-left" style="width: 120px;">
                            <select name="admin_id">
                                <option value="">选择添加人</option>
                                <?php foreach ($adminList as $value) { ?>
                                    <option value="<?= $value['id'] ?>" <?= $admin_id == $value['id'] ? 'selected' : '' ?>><?= $value['username'] ?></option>
                                <?php } ?>
                            </select>
                        </div>
                        <div class="layui-inline text-left" style="width: 120px;">
                            <select name="status">
                                <option value="">选择状态</option>
                                <option value="1" <?= $status == 1 ? 'selected' : '' ?>>正常</option>
                                <option value="0" <?= $status == 0 && strlen($status) ? 'selected' : '' ?>>已下线</option>
                                <option value="-1" <?= $status == -1 ? 'selected' : '' ?>>已关闭</option>
                            </select>
                        </div>
                        <div class="layui-inline">
                            <button class="layui-btn layuiadmin-btn-list" type="submit">
                                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="layui-card-body">
            <table class="layui-table layui-form">
                <colgroup>
                    <col width="80">
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col width="120">
                    <col width="160">
                </colgroup>
                <thead>
                <tr>
                    <th>活动ID</th>
                    <th>活动标题</th>
                    <th>活动类型</th>
                    <th>关联游戏</th>
                    <th>开始日期</th>
                    <th>结束日期</th>
                    <th>添加时间</th>
                    <th>添加人</th>
                    <th>状态</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($list as $item) { ?>
                    <tr data-id="<?= $item['id'] ?>">
                        <td><?= $item['id'] ?></td>
                        <td><?= $item['title'] ?></td>
                        <td><?= $item['type'] == 1 ? '活动公告' : '独家活动' ?></td>
                        <td><?= $item['game_name'] ?></td>
                        <td><?= date("Y-m-d H:i:s", $item['start_time']) ?></td>
                        <td><?= date("Y-m-d H:i:s", $item['end_time']) ?></td>
                        <td><?= date("Y-m-d H:i:s", $item['addtime']) ?></td>
                        <td><?= $adminInfo[$item['admin_id']]['username'] ?></td>
                        <td>
                            <select name="status" lay-select lay-filter="edit_status"
                                    data-val="<?= $item['status']; ?>">
                                <option value="1" <?= ($item['status'] == 1) ? 'selected = "selected"' : '' ?>>正常
                                </option>
                                <option value="0" <?= ($item['status'] == 0) ? 'selected = "selected"' : '' ?>>已下线
                                </option>
                                <option value="-1" <?= ($item['status'] == -1) ? 'selected = "selected"' : '' ?>>已关闭
                                </option>
                            </select>
                        </td>
                        <td>
                            <a class="layui-btn layui-btn-xs" href="/activity/edit?id=<?= $item['id'] ?>&p=<?= $p ?>">
                                <i class="layui-icon layui-icon-edit"></i>编辑
                            </a>
                            <a class="layui-btn layui-btn-xs layui-btn-danger delete">
                                <i class="layui-icon layui-icon-delete"></i>删除
                            </a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            <?= $page ?>
        </div>
    </div>
</div>

<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.extend({
        autocomplete: '/layuiadmin/autocomplete/autocomplete'
    }).use(['form', 'autocomplete'], function () {
        var $ = layui.$
            , form = layui.form
            , autocomplete = layui.autocomplete;

        // 修改状态
        form.on('select(edit_status)', function (data) {
            var id = $(this).closest('tr').data('id');
            var oldval = data.elem.getAttribute('data-val');
            var val = data.value;

            if (val != oldval) {
                updateAttr({'id': id, 'field': 'status', 'val': val}, function () {
                    $("#status_hidden_id").val(val);
                    layer.msg('操作成功', {icon: 1, time: 1000}, function () {
                        window.location.reload()
                    });
                });
            }
        });

        var updateAttr = function (data, callback) {
            $.ajax({
                type: "post",
                dataType: "json",
                url: "/activity/toggle",
                data: data,
                success: function (json) {
                    if (json.code == 200) {
                        callback();
                    } else {
                        layer.alert(json.msg);
                    }
                }
            });
        };

        function batchdel(ids, callback) {
            $.ajax({
                type: "post",
                dataType: "json",
                url: "/activity/toggle",
                data: {"id": ids, 'field': 'status', 'val': -1},
                success: function (json) {
                    if (json.code == 200) {
                        layer.msg('删除成功', {icon: 1, time: 1000}, function () {
                            if (typeof callback == 'function') callback();
                        });
                    } else {
                        layer.alert(json.msg)
                    }
                }
            })
        }

        //单个删除
        $('.delete').on('click', function () {
            var tr = $(this).closest('tr');
            var ids = tr.data('id');
            layer.confirm('确定要删除吗？', {btn: ['确定', '取消']}, function () {
                batchdel(ids, function () {
                    tr.remove();
                });
            });
        });

        // 搜索活动
        $('#activity_name').on('keydown', function (event) {
            if (event.keyCode == 8) {
                $('input[name="activity_name"]').val('')
                $('input[name="activity_id"]').val('')
            }
        });
        autocomplete.init({
            elem: "#activity_name",
            textLength: 2,//触发长度
            delay: 200,//触发延迟
            callback: {
                data: function (val, render) {
                    $.ajax({
                        type: "post",
                        dataType: "json",
                        url: "/activity/autocomplete",
                        data: {name: val},
                        success: function (json) {
                            if (json.code == 200) {
                                render(json.data);
                            } else {
                                layer.alert(json.msg);
                            }
                        }
                    });
                },
                selected: function (data) {
                    console.log(data);
                    $('input[name="activity_id"]').val(data.value)
                },
                close: function () {
                }
            }
        });

        // 搜索游戏
        $('#game_name').on('keydown', function (event) {
            if (event.keyCode == 8) {
                $('input[name="game_id"]').val('')
            }
        });
        autocomplete.init({
            elem: "#game_name",
            textLength: 2,//触发长度
            delay: 200,//触发延迟
            callback: {
                data: function (val, render) {
                    $.ajax({
                        type: "post",
                        dataType: "json",
                        url: "/game/autocomplete",
                        data: {name: val},
                        success: function (json) {
                            if (json.code == 200) {
                                render(json.data);
                            } else {
                                layer.alert(json.msg);
                            }
                        }
                    });
                },
                selected: function (data) {
                    console.log(data);
                    $('input[name="game_id"]').val(data.value)
                },
                close: function () {
                }
            }
        });

    });
</script>
</body>
</html>
