<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>
<body>
<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-form layui-card-header layuiadmin-card-header-auto">
            <div class="layui-form-item">
                <div class="layui-inline">
                    <a class="layui-btn" href="/recommend_type/add">添加</a>
                </div>
            </div>
        </div>

        <div class="layui-card-body">
            <table class="layui-table layui-form">
                <colgroup>
                    <col width="40">
                    <col>
                    <col>
                    <col>
                    <col>
                    <col width="160">
                </colgroup>
                <thead>
                <tr>
                    <th>排序</th>
                    <th>编号</th>
                    <th>推荐位名称</th>
                    <th>推荐详情(展示中)</th>
                    <th>待确认游戏数</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($list as $item) { ?>
                    <tr data-id="<?= $item['id'] ?>">
                        <td><input type="text" name="sort" class="table-text sort" data-val="<?= $item['sort']; ?>"
                                   value="<?= $item['sort']; ?>"></td>
                        <td><?= $item['id'] ?></td>
                        <td><?= $item['name'] ?></td>
                        <td><a href="/recommend_game/index?type_id=<?=$item['id'] ?>&last_page=<?= $p ?>">共计<?= $item['true_num'] ?>款游戏>></a></td>
                        <td><?= $item['false_num'] ?></td>
                        <td>
                            <a class="layui-btn layui-btn-xs" href="/recommend_type/edit?id=<?=$item['id']?>&p=<?= $p ?>"><i class="layui-icon layui-icon-edit"></i>修改</a>
                            <a class="layui-btn layui-btn-xs layui-btn-danger delete">
                                <i class="layui-icon layui-icon-delete"></i>删除
                            </a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            <?=$page?>
        </div>
    </div>
</div>

<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.use('form', function () {
        var $ = layui.$
            , form = layui.form;

        //添加
        form.on('submit(recommend-type-add)', function (obj) {
            $.ajax({
                url: '/recommend_type/add',
                type: "POST",
                dataType: "JSON",
                data: obj.field,
                success: function (resp) {
                    if (resp.code == 200) {
                        layer.msg('添加成功', {icon: 1, time: 1000}, function () {
                            location.href = location.href;
                        });
                    } else {
                        layer.msg(resp.msg, {icon: 5, time: 1000});
                    }
                }
            })
        });

        function batchdel(ids, callback) {
            $.ajax({
                type: "post",
                dataType: "json",
                url: "/recommend_type/delete",
                data: {"ids": ids},
                success: function (json) {
                    if (json.code == 200) {
                        layer.msg('删除成功', {icon: 1, time: 1000}, function () {
                            if (typeof callback == 'function') callback();
                        });
                    } else {
                        layer.alert(json.msg)
                    }
                }
            })
        }

        //单个删除
        $('.delete').on('click', function () {
            var ids = [];
            var tr = $(this).closest('tr');
            ids.push(tr.data('id'));
            layer.confirm('确定要删除吗？', {btn: ['确定', '取消']}, function () {
                batchdel(ids, function () {
                    tr.remove();
                });
            });
        });

        //分类排序
        $('.sort').on('blur', function () {
            var id = $(this).closest('tr').data('id');
            var oldval = parseInt($(this).data('val'));
            var sort = parseInt($(this).val());
            var self = $(this);
            if (sort >= 0 && oldval != sort) {
                updateAttr({'id': id, 'field': 'sort', 'val': sort}, function () {
                    $("input[name='sort']").data('val', sort);
                    layer.msg('操作成功', {icon: 1, time: 1000});
                });
            }
        });

        var updateAttr = function (data, callback) {
            $.ajax({
                type: "post",
                dataType: "json",
                url: "/recommend_type/toggle",
                data: data,
                success: function (json) {
                    if (json.code == 200) {
                        callback();
                    } else {
                        layer.alert(json.msg);
                    }
                }
            });
        }


    });
</script>
</body>
</html>