<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>
<body>
<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-form layui-card-header layuiadmin-card-header-auto">
            <div class="layui-form-item">
                <div class="layui-inline">
                    <input type="text" name="name" value="" placeholder="输入主题名称" autocomplete="off" class="layui-input">
                </div>
                <div class="layui-inline">
                    <button class="layui-btn" lay-submit lay-filter="game-topic-cate-add">添加</button>
                </div>
            </div>
        </div>

        <div class="layui-card-body">
            <table class="layui-table layui-form">
                <colgroup>
                    <col>
                    <col>
                    <col>
                    <col width="160">
                </colgroup>
                <thead>
                <tr>
                    <th>主题ID</th>
                    <th>主题名称</th>
                    <th>排序</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($list as $item) { ?>
                    <tr data-id="<?= $item['id'] ?>">
                        <td><?= $item['id'] ?></td>
                        <td><input type="text" name="name" class="table-text" value="<?= $item['name'] ?>"></td>
                        <td><input type="text" name="sort" class="table-text" value="<?= $item['sort']; ?>"></td>
                        <td>
                            <a class="layui-btn layui-btn-xs edit">
                                <i class="layui-icon layui-icon-edit"></i>修改
                            </a>
                            <a class="layui-btn layui-btn-xs layui-btn-danger delete">
                                <i class="layui-icon layui-icon-delete"></i>删除
                            </a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            <?= $page ?>
        </div>
    </div>
</div>

<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.use('form', function () {
        var $ = layui.$
            , form = layui.form;

        //添加
        form.on('submit(game-topic-cate-add)', function (obj) {
            $.ajax({
                url: '/game_topic/add',
                type: "POST",
                dataType: "JSON",
                data: obj.field,
                success: function (resp) {
                    if (resp.code == 200) {
                        layer.msg('添加成功', {icon: 1, time: 1000}, function () {
                            location.href = location.href;
                        });
                    } else {
                        layer.msg(resp.msg, {icon: 5, time: 1000});
                    }
                }
            })
        });

        //修改
        $('.edit').on('click', function () {
            var tr = $(this).closest('tr');
            var id = tr.data('id');
            var name = tr.find('input[name="name"]').val();
            var sort = tr.find('input[name="sort"]').val();
            $.ajax({
                type: "POST",
                dataType: "JSON",
                url: '/game_topic/edit',
                data: {"id": id, "name":name,"sort": sort},
                success: function (json) {
                    if (json.code == 200) {
                        layer.msg('修改成功', {icon: 1, time: 800}, function () {
                            location.href = location.href;
                        });
                    } else {
                        layer.alert(json.msg)
                    }
                }
            })
        });


        function batchdel(ids, callback) {
            $.ajax({
                type: "post",
                dataType: "json",
                url: "/game_topic/delete",
                data: {"ids": ids},
                success: function (json) {
                    if (json.code == 200) {
                        layer.msg('删除成功', {icon: 1, time: 1000}, function () {
                            if (typeof callback == 'function') {
                                callback();
                            }
                        });
                    } else {
                        layer.alert(json.msg)
                    }
                }
            })
        }

        //单个删除
        $('.delete').on('click', function () {
            var ids = [];
            var tr = $(this).closest('tr');
            ids.push(tr.data('id'));
            layer.confirm('确定要删除吗？', {btn: ['确定', '取消']}, function () {
                batchdel(ids, function () {
                    tr.remove();
                });
            });
        });

    });
</script>
</body>
</html>