<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>

<body>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">编辑渠道公告</div>
                <div class="layui-card-body" pad15="">
                    <div class="layui-form" lay-filter="">
                        <input type="hidden" name="id" value="<?= $info['id'] ?? '' ?>">
                        <div class="layui-form-item">
                            <label class="layui-form-label">标题</label>
                            <div class="layui-input-inline">
                                <input type="text" name="title" value="<?= $info['title'] ?? '' ?>" placeholder="请输入标题"
                                       lay-verify="required" lay-verType="tips" autocomplete="off" class="layui-input">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">内容</label>
                            <div class="layui-input-inline" style="width: 600px">
                                <textarea name="content" placeholder="请输入内容" lay-verify="required" lay-verType="tips" class="layui-textarea"><?= $info['content'] ?? '' ?></textarea>
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <button class="layui-btn" lay-submit lay-filter="channel-announcement-edit">提交</button>
                                <a class="layui-btn layui-btn-primary" href="/channel_announcement/index?p=<?= $p ?>">返回</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.use(['form', 'layer'], function () {
        var $ = layui.$,
            form = layui.form,
            layer = layui.layer;

        form.on('submit(channel-announcement-edit)', function (obj) {
            $.ajax({
                url: '/channel_announcement/edit',
                type: "POST",
                dataType: "JSON",
                data: obj.field,
                success: function (resp) {
                    if (resp.code == 200) {
                        layer.msg('编辑成功', {icon: 1, time: 1000}, function () {
                            location.href = '/channel_announcement/index?p=<?= $p ?>';
                        });
                    } else {
                        layer.msg(resp.msg, {icon: 5, time: 1000});
                    }
                }
            })
        });
    });
</script>
</body>
</html>