<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>
<body>

<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header"><?= empty($info) ? '添加常见问题' : '编辑常见问题' ?></div>
                <div class="layui-card-body" pad15>
                    <div class="layui-form" lay-filter="">
                        <div class="layui-form-item">
                            <label class="layui-form-label">问题分类</label>
                            <div class="layui-input-inline">
                                <select name="cate_id" lay-verify="required" lay-verType="tips">
                                    <option value="0">-- 无 --</option>
                                    <?php foreach ($cates as $cate) { ?>
                                        <option value="<?= $cate['id'] ?>" <?php if (isset($info['cate_id']) && $info['cate_id'] == $cate['id']) {
                                            echo 'selected';
                                        } ?>><?= $cate['name'] ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">标题</label>
                            <div class="layui-input-inline">
                                <input type="text" name="title" value="<?= $info['title'] ?? '' ?>"
                                       lay-verify="required" lay-verType="tips" autocomplete="off" class="layui-input">
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">排序</label>
                            <div class="layui-input-inline">
                                <input type="text" name="sort" value="<?= $info['sort'] ?? '' ?>" placeholder=""
                                       lay-verify="required" lay-verType="tips" autocomplete="off" class="layui-input">
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">内容</label>
                            <div class="layui-input-block">
                                <textarea name="content" class="layui-textarea" lay-verify="required"
                                          lay-verType="tips"><?= $info['content'] ?? '' ?></textarea>
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <input type="hidden" name="id" value="<?= $info['id'] ?? '' ?>">
                                <button class="layui-btn" lay-submit lay-filter="faq-add">提交</button>
                                <a class="layui-btn layui-btn-primary" href="/faq/index?p=<?= $p ?>">返回</a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.use('form', function () {
        var $ = layui.$
            , form = layui.form
            , layer = layui.layer;

        /*form.verify({
            nickname: [/^[\S]{2,16}$/, '昵称最少2个字符'],
        })*/

        form.on('submit(faq-add)', function (obj) {
            $.ajax({
                url: '/faq/add',
                type: "POST",
                dataType: "JSON",
                data: obj.field,
                success: function (resp) {
                    if (resp.code == 200) {
                        layer.msg('添加成功', {icon: 1, time: 1000}, function () {
                            location.href = '/faq/index';
                        });
                    } else {
                        layer.msg(resp.msg, {icon: 5, time: 1000});
                    }
                }
            })
        });
    });
</script>
</body>
</html>