<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>

<body>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">编辑推荐游戏</div>
                <div class="layui-card-body" pad15>
                    <div class="layui-form" lay-filter="">
                        <div class="layui-form-item">
                            <label class="layui-form-label">游戏名称</label>
                            <div class="layui-input-inline">
                                <input type="text" class="layui-input" disabled value="<?= $game_name ?>">
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">标签</label>
                            <div class="layui-input-inline">
                                <input type="text" name="tag" value="<?= $info['tag'] ?>" lay-verify="required"
                                       lay-verType="tips" autocomplete="off" class="layui-input">
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">描述</label>
                            <div class="layui-input-inline">
                                <input type="text" name="des" value="<?= $info['des'] ?>" lay-verify="required"
                                       lay-verType="tips" autocomplete="off" class="layui-input">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">展示图</label>
                            <div class="layui-input-block" id="pictures_badge">
                                <input type="hidden" name="badge" value="<?= $info['img'] ?? '' ?>">
                                <img src="<?= $info['img'] ?? '' ?>" class="layui-upload-img" id="img-badge"/>
                                <button type="button" class="layui-btn layui-btn-primary" id="selectfiles_badge"><i
                                            class="layui-icon">&#xe67c;</i>上传图片
                                </button>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <input type="hidden" name="id" value="<?= $info['id'] ?>">
                                <input type="hidden" name="type_id" value="<?= $info['type_id'] ?>">
                                <button class="layui-btn" lay-submit lay-filter="recommend-game-edit">提交</button>
                                <a class="layui-btn layui-btn-primary" href="/recommend_game/index?p=<?= $p ?>&type_id=<?= $type_id ?>&last_page=<?= $last_page ?>">返回</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script type="text/javascript" src="/common/js/plupload-2.1.2/js/plupload.full.min.js"></script>
<script type="text/javascript" src="/common/js/oss.upload.lib.js?t=20190402"></script>
<script>
    layui.use('form', function () {
        var $ = layui.$
            , form = layui.form
            , layer = layui.layer;


        form.on('submit(recommend-game-edit)', function (obj) {
            $.ajax({
                url: '/recommend_game/edit',
                type: "POST",
                dataType: "JSON",
                data: obj.field,
                success: function (resp) {
                    if (resp.code == 200) {
                        layer.msg('修改成功', {icon: 1, time: 1000}, function () {
                            location.href = '/recommend_game/index?type_id=' + $('input[name="type_id"]').val();
                            ;
                        });
                    } else {
                        layer.msg(resp.msg, {icon: 5, time: 1000});
                    }
                }
            })
        });

        // 展示图
        var callback_img = function (imgurl) {
            $('input[name="badge"]').val(imgurl);
            $('#img-badge').attr('src', imgurl).show();
        };

        var img_upload = new ossUpload();
        img_upload.init({
            container_id: 'pictures_badge',
            browse_button: 'selectfiles_badge',
            serverUrl: '/oss/get_token',
            width: 100,
            height: 100,
            wh_model: 'eq',
            callback: callback_img,
        });

    });
</script>
</body>
</html>