<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>
<body>
<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-card-header layuiadmin-card-header-auto">
            <div class="layui-form layui-input-inline">
                <div class="layui-form-item">
                    <div class="layui-inline">
                        <input type="hidden" name="game_id" value="">
                        <input type="text" name="game_name" id="game_name" value="" class="layui-input" placeholder="游戏名称" autocomplete="off">
                    </div>
                    <div class="layui-inline">
                        <input type="text" name="name" value="" placeholder="区服" autocomplete="off" class="layui-input">
                    </div>
                    <div class="layui-inline">
                        <input type="text" class="layui-input" name="start_time" id="start-time" autocomplete="off" placeholder="开服时间">
                    </div>
                    <div class="layui-inline">
                        <button class="layui-btn" lay-submit lay-filter="game-server-preview-add">添加</button>
                    </div>
                </div>
            </div>
            <div class="layui-form layui-input-inline" style="float: right">
                <div class="layui-form-item">
                    <div class="layui-inline">
                        <input type="hidden" name="file_game_id" id="file_game_id" value="">
                        <input type="text" name="file_game_name" id="file_game_name" value="" class="layui-input" placeholder="游戏名称" autocomplete="off">
                    </div>

                    <div class="layui-inline">
                        <button type="button" class="layui-btn" id="import_public">导入游戏服</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="layui-card-body">
            <table class="layui-table layui-form">
                <colgroup>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col width="160">
                </colgroup>
                <thead>
                <tr>
                    <th>ID</th>
                    <th>游戏名</th>
                    <th>区服信息</th>
                    <th>开服时间</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($list as $item) { ?>
                    <tr data-id="<?= $item['id'] ?>">
                        <td><?= $item['id'] ?></td>
                        <td><?= $game[$item['game_id']]['name'] ?></td>
                        <td><input type="text" name="name" class="table-text" value="<?= $item['name']; ?>"></td>
                        <td><?= $item['start_time'] >0 ? date('Y-m-d H:i:s', $item['start_time'])  : '' ?></td>
                        <td>
                            <a class="layui-btn layui-btn-xs edit">
                                <i class="layui-icon layui-icon-edit"></i>修改
                            </a>
                            <a class="layui-btn layui-btn-xs layui-btn-danger delete">
                                <i class="layui-icon layui-icon-delete"></i>删除</a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            <?=$page?>
        </div>
    </div>
</div>

<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script type="text/javascript" src="/common/js/plupload-2.1.2/js/plupload.full.min.js"></script>
<script type="text/javascript" src="/common/js/oss.upload.lib.js?t=20190402"></script>
<script>
    layui.extend({
        autocomplete: '/layuiadmin/autocomplete/autocomplete'
    }).use(['form', 'autocomplete', 'laydate', 'upload'], function () {
        var $ = layui.$,
            form = layui.form
            , upload = layui.upload
            , autocomplete = layui.autocomplete
            , laydate = layui.laydate;

        /** 导入 **/
        //指定允许上传的文件类型
            upload.render({
                elem: '#import_public',
                url: '/game_server_preview/import',
                accept: 'file', //普通文件
                data: {
                    game_id: function(){ return $("#file_game_id").val(); }
                },
                done: function(res){
                    if (res.code == 200) {
                        console.log(res);
                        layer.msg(res.msg, {icon: 1, time: 1000}, function () {
                            setTimeout(function () {
                                window.location.reload();
                            }, 1000)
                        });
                    }else {
                        console.log(res);
                        layer.msg(res.msg, {icon: 5, time: 1000});
                    }
                }
            });

        //日期时间选择器
        laydate.render({
            elem: '#start-time',
            type: 'datetime'
        });


        //搜索游戏
        $('#game_name').on('keydown', function (event) {
            if (event.keyCode == 8) {
                $('input[name="id"]').val('')
            }
        });
        autocomplete.init({
            elem: "#game_name",
            textLength: 2,//触发长度
            delay: 200,//触发延迟
            callback: {
                data: function (val, render) {
                    $.ajax({
                        type: "post",
                        dataType: "json",
                        url: "/game/autocomplete",
                        data: {name: val},
                        success: function (json) {
                            if (json.code == 200) {
                                render(json.data);
                            } else {
                                layer.alert(json.msg);
                            }
                        }
                    });
                },
                selected: function (data) {
                    console.log(data)
                    $('input[name="game_id"]').val(data.value)
                },
                close: function () {
                }
            }
        });

        //搜索游戏
        $('#file_game_name').on('keydown', function (event) {
            if (event.keyCode == 8) {
                $('input[name="file_game_id"]').val('')
            }
        });
        autocomplete.init({
            elem: "#file_game_name",
            textLength: 2,//触发长度
            delay: 200,//触发延迟
            callback: {
                data: function (val, render) {
                    $.ajax({
                        type: "post",
                        dataType: "json",
                        url: "/game/autocomplete",
                        data: {name: val},
                        success: function (json) {
                            if (json.code == 200) {
                                render(json.data);
                            } else {
                                layer.alert(json.msg);
                            }
                        }
                    });
                },
                selected: function (data) {
                    console.log(data);
                    $('input[name="file_game_id"]').val(data.value)
                },
                close: function () {
                }
            }
        });


        //添加
        form.on('submit(game-server-preview-add)', function (obj) {
            $.ajax({
                url: '/game_server_preview/add',
                type: "POST",
                dataType: "JSON",
                data: obj.field,
                success: function (resp) {
                    if (resp.code == 200) {
                        layer.msg('添加成功', {icon: 1, time: 1000}, function () {
                            location.href = location.href;
                        });
                    } else {
                        layer.msg(resp.msg, {icon: 5, time: 1000});
                    }
                }
            })
        });

        //修改
        $('.edit').on('click', function () {
            var tr = $(this).closest('tr');
            var id = tr.data('id');
            var name = tr.find('input[name="name"]').val();
            $.ajax({
                type: "POST",
                dataType: "JSON",
                url: '/game_server_preview/edit',
                data: {"id": id, "name": name},
                success: function (json) {
                    if (json.code == 200) {
                        layer.msg('修改成功', {icon: 1, time: 800}, function () {
                            location.href = location.href;
                        });
                    } else {
                        layer.alert(json.msg)
                    }
                }
            })
        });

        //单个删除
        $('.delete').on('click', function () {
            var ids = [];
            var tr = $(this).closest('tr');
            ids.push(tr.data('id'));
            layer.confirm('确定要删除吗？', {btn: ['确定', '取消']}, function () {
                batchdel(ids, function () {
                    tr.remove();
                });
            });
        });

        function batchdel(ids, callback) {
            $.ajax({
                type: "post",
                dataType: "json",
                url: "/game_server_preview/delete",
                data: {"ids": ids},
                success: function (json) {
                    if (json.code == 200) {
                        layer.msg('删除成功', {icon: 1, time: 1000}, function () {
                            if (typeof callback == 'function') {
                                callback();
                            }
                        });
                    } else {
                        layer.alert(json.msg)
                    }
                }
            })
        }

    });
</script>
</body>
</html>