<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>

<body>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">后台直冲平台币</div>
                <div class="layui-card-body">
                    <div class="layui-form" lay-filter="">
                        <div class="layui-form-item">
                            <label class="layui-form-label">用户名</label>
                            <div class="layui-input-inline">
                                <input type="hidden" name="user_id" id="user_id" value="">
                                <input type="text" id="user_name" lay-verify="required"
                                       placeholder="请输入用户名" lay-verType="tips" autocomplete="off" class="layui-input">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">充值额度</label>
                            <div class="layui-input-inline">
                                <input type="text" name="coin" value="" lay-verify="required"
                                       placeholder="请输入充值额度" lay-verType="tips" autocomplete="off" class="layui-input">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">类型</label>
                            <div class="layui-input-inline">
                                <select name="income_type" lay-verify="">
                                    <option value="">请选择获取类型</option>
                                    <?php foreach ($incomeType as $v) { ?>
                                        <option value="<?= $v['id'] ?>" <?=$v['id'] == 6 ? 'selected' : ''?>><?= $v['name'] ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">备注</label>
                            <div class="layui-input-block">
                                <textarea name="remarks" lay-verify="required" placeholder="请输入备注"
                                                     class="layui-textarea"></textarea>
                            </div>
                        </div>

                        <div class="layui-form-item">
                            <div class="layui-input-block">
<!--                                <a class="layui-btn layui-btn-primary" href="javascript:void(0);"-->
<!--                                   onclick="history.go(-1)">返回</a>-->
                                <button class="layui-btn" lay-submit lay-filter="backend-charge-add">提交</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.extend({
        autocomplete: "/layuiadmin/autocomplete/autocomplete"
    }).use(['form', 'autocomplete'], function () {
            var $ = layui.$,
                autocomplete = layui.autocomplete,
                form = layui.form;

            form.on('submit(backend-charge-add)', function (obj) {
                $.ajax({
                    url: '/backend_charge/add',
                    type: "POST",
                    dataType: "JSON",
                    data: obj.field,
                    success: function (resp) {
                        if (resp.code == 200) {
                            layer.msg('添加成功', {icon: 1, time: 1000}, function () {
                                location.href = '/backend_charge/add';
                            });
                        } else {
                            layer.msg(resp.msg, {icon: 5, time: 1000});
                        }
                    }
                })
            });

        // 搜索用户
        $('#user_name').on('keydown', function (event) {
            if (event.keyCode == 8) {
                $('input[name="user_id"]').val('')
            }
        });
        autocomplete.init({
            elem: "#user_name",
            textLength: 2,//触发长度
            delay: 200,//触发延迟
            callback: {
                data: function (val, render) {
                    $.ajax({
                        type: "post",
                        dataType: "json",
                        url: "/user/autocomplete",
                        data: {name: val},
                        success: function (json) {
                            if (json.code == 200) {
                                render(json.data);
                            } else {
                                layer.alert(json.msg);
                            }
                        }
                    });
                },
                selected: function (data) {
                    console.log(data);
                    $('input[name="user_id"]').val(data.value)
                },
                close: function () {
                }
            }
        });

        }
    );
</script>
</body>
</html>