<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>
<body>
<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-form layui-card-header layuiadmin-card-header-auto" style="line-height: normal;">
            <div class="layui-form-item">
                <div class="layui-inline">
                    <input type="text" name="name" value="" placeholder="请输入标签名" lay-verify="required"
                           lay-verType="tips" autocomplete="off" class="layui-input">
                </div>
                <div class="layui-inline">
                    <input type="text" name="color" value="" placeholder="请选择颜色" lay-verify="required"
                           lay-verType="tips" class="layui-input" id="colorpicker-form-input">
                </div>
                <div class="layui-inline">
                    <div class="colorpicker-des"></div>
                </div>
                <div class="layui-inline">
                    <button class="layui-btn" lay-submit lay-filter="tags-add">添加</button>
                </div>
            </div>
        </div>

        <div class="layui-card-body">
            <table class="layui-table layui-form">
                <colgroup>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col width="160">
                </colgroup>
                <thead>
                <tr>
                    <th>标签ID</th>
                    <th>标签名称</th>
                    <th>颜色</th>
                    <th>添加人</th>
                    <th>添加时间</th>
                    <th>状态</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($list as $item) { ?>
                    <tr data-id="<?= $item['id'] ?>">
                        <td><?= $item['id'] ?></td>
                        <td><input type="text" name="name" class="layui-input" style="width: 152px;"
                                   value="<?= $item['name'] ?>"></td>
                        <td>
                            <div class="layui-input-inline" style="width: 152px;">
                                <input type="text" name="color" value="<?= $item['color'] ?>" placeholder="请选择颜色"
                                       lay-verify="required" lay-verType="tips"
                                       class="layui-input colorpicker-edit-input">
                            </div>
                            <div class="layui-inline">
                                <div class="colorpicker-edit-div"></div>
                            </div>
                        </td>
                        <td><?= $item['admin_id'] ?></td>
                        <td><?= date('Y-m-d H:i:s', $item['addtime']) ?></td>
                        <td><input type="checkbox" value="1" lay-filter="status"
                                   name="status" <?= ($item['status'] == 1) ? 'checked' : '' ?> lay-skin="switch"
                                   lay-text="开启|关闭"></td>
                        <td>
                            <a class="layui-btn layui-btn-xs edit">
                                <i class="layui-icon layui-icon-edit"></i>修改
                            </a>
                            <a class="layui-btn layui-btn-xs layui-btn-danger delete">
                                <i class="layui-icon layui-icon-delete"></i>删除
                            </a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            <?= $page ?>
        </div>
    </div>
</div>

<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.use(['form', 'colorpicker'], function () {
        var $ = layui.$,
            form = layui.form,
            colorpicker = layui.colorpicker;

        //添加标签
        form.on('submit(tags-add)', function (obj) {
            $.ajax({
                url: '/tags/add',
                type: "POST",
                dataType: "JSON",
                data: obj.field,
                success: function (resp) {
                    if (resp.code == 200) {
                        layer.msg('添加成功', {icon: 1, time: 1000}, function () {
                            location.href = location.href;
                        });
                    } else {
                        layer.msg(resp.msg, {icon: 5, time: 1000});
                    }
                }
            })
        });

        //启用禁用
        form.on('switch(status)', function (data) {
            console.log(data.elem.checked);
            var id = $(this).closest('tr').data('id');
            var val = data.elem.checked ? 1 : 0;
            $.ajax({
                type: "post",
                dataType: "json",
                url: "/tags/toggle",
                data: {id: id, field: 'status', val: val},
                success: function (json) {
                    if (json.code == 200) {
                        layer.msg('操作成功');
                    } else {
                        layer.alert(json.msg);
                    }
                }
            });
        });


        //修改
        $('.edit').on('click', function () {
            var tr = $(this).closest('tr');
            var id = tr.data('id');
            var name = tr.find('input[name="name"]').val();
            var color = tr.find('input[name="color"]').val();
            $.ajax({
                type: "POST",
                dataType: "JSON",
                url: '/tags/edit',
                data: {"id": id, "name": name, "color": color},
                success: function (json) {
                    if (json.code == 200) {
                        layer.msg('修改成功', {icon: 1, time: 800}, function () {
                            location.href = location.href;
                        });
                    } else {
                        layer.alert(json.msg)
                    }
                }
            })
        });

        //单个删除
        $('.delete').on('click', function () {
            var ids = [];
            var tr = $(this).closest('tr');
            ids.push(tr.data('id'));
            layer.confirm('确定要删除吗？', {btn: ['确定', '取消']}, function () {
                batchdel(ids, function () {
                    tr.remove();
                });
            });
        });

        function batchdel(ids, callback) {
            $.ajax({
                type: "post",
                dataType: "json",
                url: "/tags/delete",
                data: {"ids": ids},
                success: function (json) {
                    if (json.code == 200) {
                        layer.msg('删除成功', {icon: 1, time: 1000}, function () {
                            if (typeof callback == 'function') {
                                callback();
                            }
                        });
                    } else {
                        layer.alert(json.msg)
                    }
                }
            })
        }

        //颜色选择器
        colorpicker.render({
            elem: '.colorpicker-des',
            color: '#999999',
            done: function (color) {
                $('#colorpicker-form-input').val(color);
            }
        })


        $('.colorpicker-edit-input').each(function () {
            var self = $(this);
            elem = $(this).closest('td').find('div.colorpicker-edit-div');
            //颜色选择器
            colorpicker.render({
                elem: elem,
                size: 'xs',
                color: self.val(),
                done: function (color) {
                    self.val(color);
                }
            })
        })
    });
</script>
</body>
</html>