<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>
<body>

<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">

            <div class="layui-card">
                <div class="layui-card-header">协议编辑</div>
                <div class="layui-card-body">
                    <div class="layui-tab layui-tab-card">
                        <ul class="layui-tab-title">
                            <li class="layui-this">注册协议</li>
                            <li>隐私协议</li>
                        </ul>
                        <div class="layui-tab-content">
                            <div class="layui-tab-item layui-show">
                                <div class="layui-form" lay-filter="">
                                    <div class="layui-form-item">
                                        <div class="layui-input-block" style="margin-left: 0;">
                                            <textarea name="des" class="layui-textarea" style="width:100%; height: 450px;"><?=$agreement['register']['des'] ?? ''?></textarea>
                                        </div>
                                    </div>
                                    <div class="layui-form-item">
                                        <div class="layui-input-inline">
                                            <input type="hidden" name="const" value="register">
                                            <button class="layui-btn" lay-submit lay-filter="register-agreement-edit">提交</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="layui-tab-item">
                                <div class="layui-form" lay-filter="">
                                    <div class="layui-form-item">
                                        <div class="layui-input-block" style="margin-left: 0;">
                                            <textarea name="des" class="layui-textarea" style="width:100%; height: 450px;"><?=$agreement['privacy']['des'] ?? ''?></textarea>
                                        </div>
                                    </div>
                                    <div class="layui-form-item">
                                        <div class="layui-input-inline">
                                            <input type="hidden" name="const" value="privacy">
                                            <button class="layui-btn" lay-submit lay-filter="privacy-agreement-edit">提交</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.use(['form', 'element'], function () {
        var $ = layui.$
            , form = layui.form
            , layer = layui.layer
            ,element = layui.element;

        element.render();

        /*form.verify({
            nickname: [/^[\S]{2,16}$/, '昵称最少2个字符'],
        })*/

        form.on('submit(register-agreement-edit)', function (obj) {
            ajaxEdit(obj);
        });
        form.on('submit(privacy-agreement-edit)', function (obj) {
            ajaxEdit(obj);
        });

        var ajaxEdit = function (obj) {
            $.ajax({
                url: '/agreement/index',
                type: "POST",
                dataType: "JSON",
                data: obj.field,
                success: function (resp) {
                    if (resp.code == 200) {
                        layer.msg('修改成功', {icon: 1, time: 1000});
                    } else {
                        layer.msg(resp.msg, {icon: 5, time: 1000});
                    }
                }
            })
        }
    });
</script>
</body>
</html>