<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>

<body>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">添加研发商</div>
                <div class="layui-card-body" pad15>

                    <div class="layui-form" lay-filter="">
                        <div class="layui-form-item">
                            <label class="layui-form-label">简称</label>
                            <div class="layui-input-inline">
                                <input type="text" name="name" value="" lay-verify="required" lay-verType="tips"
                                       autocomplete="off" class="layui-input" placeholder="请输入研发商简称">
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">公司名称</label>
                            <div class="layui-input-inline">
                                <input type="text" name="company_name" value="" lay-verify="required" lay-verType="tips"
                                       autocomplete="off" class="layui-input" placeholder="请输入公司名称">
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">联系人</label>
                            <div class="layui-input-inline">
                                <input type="text" name="contacts" value="" lay-verify="required" lay-verType="tips"
                                       autocomplete="off" class="layui-input" placeholder="请输入联系人姓名">
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">联系方式</label>
                            <div class="layui-input-block">
                                <textarea name="contacts_des" class="layui-textarea" placeholder="请输入联系方式"
                                          lay-verify="required" lay-verType="tips"></textarea>
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">账户类型</label>
                            <div class="layui-input-block">
                                <input type="radio" name="account_type" value="1" title="对公" checked>
                                <input type="radio" name="account_type" value="2" title="对私">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">收款户名</label>
                            <div class="layui-input-inline">
                                <input type="text" name="payee" value="" lay-verify="required" lay-verType="tips"
                                       autocomplete="off" class="layui-input" placeholder="请输入收款户名">
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">开户行</label>
                            <div class="layui-input-inline">
                                <input type="text" name="bank" value="" lay-verify="required" lay-verType="tips"
                                       autocomplete="off" class="layui-input" placeholder="请输入开户行名">
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">账号</label>
                            <div class="layui-input-inline">
                                <input type="text" name="card_no" value="" lay-verify="required" lay-verType="tips"
                                       autocomplete="off" class="layui-input" placeholder="请输入账号">
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">备注</label>
                            <div class="layui-input-block">
                                <textarea name="des" class="layui-textarea" lay-verify="required" lay-verType="tips"
                                          placeholder="请输入备注"></textarea>
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <button class="layui-btn" lay-submit lay-filter="developer-add">提交</button>
                                <a class="layui-btn layui-btn-primary" href="javascript:void(0);"
                                   onclick="history.go(-1)">返回</a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.use('form', function () {
        var $ = layui.$
            , form = layui.form
            , layer = layui.layer;

        /*form.verify({
            nickname: [/^[\S]{2,16}$/, '昵称最少2个字符'],
        })*/

        form.on('submit(developer-add)', function (obj) {
            $.ajax({
                url: '/developer/add',
                type: "POST",
                dataType: "JSON",
                data: obj.field,
                success: function (resp) {
                    if (resp.code == 200) {
                        layer.msg('添加成功', {icon: 1, time: 1000}, function () {
                            location.href = '/developer/index';
                        });
                    } else {
                        layer.msg(resp.msg, {icon: 5, time: 1000});
                    }
                }
            })
        });
    });
</script>
</body>
</html>