<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>
<body>
<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-card-body">
            <div style="padding-bottom: 10px;">
                <a class="layui-btn" href="/developer/add">添加</a>
            </div>
            <table class="layui-table layui-form">
                <colgroup>
                    <col width="60">
                    <col>
                    <col>
                    <col>
                    <col width="180">
                    <col>
                    <col>
                    <col>
                    <col width="180">
                    <col width="160">
                </colgroup>
                <thead>
                <tr>
                    <th>编号</th>
                    <th>简称</th>
                    <th>公司名称</th>
                    <th>联系人</th>
                    <th>联系方式</th>
                    <th>收款户名</th>
                    <th>开户行</th>
                    <th>账号</th>
                    <th>备注</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($list as $item){?>
                    <tr data-id="<?=$item['id']?>">
                        <td><?=$item['id']?></td>
                        <td><?=$item['name']?></td>
                        <td><?=$item['company_name']?></td>
                        <td><?=$item['contacts']?></td>
                        <td><?=$item['contacts_des']?></td>
                        <td><?=$item['payee']?></td>
                        <td><?=$item['bank']?></td>
                        <td><?=$item['card_no']?></td>
                        <td><?=$item['des']?></td>
                        <td>
                            <a class="layui-btn layui-btn-xs" href="/developer/edit?id=<?=$item['id']?>&p=<?= $p ?>">
                                <i class="layui-icon layui-icon-edit"></i>编辑
                            </a>
                            <a class="layui-btn layui-btn-danger layui-btn-xs delete">
                                <i class="layui-icon layui-icon-delete"></i>删除
                            </a>
                        </td>
                    </tr>
                <?php }?>
                </tbody>
            </table>
            <?= $page ?>
        </div>
    </div>
</div>

<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.use('form', function () {
        var $ = layui.$
            , form = layui.form;


        function batchdel(ids, callback) {
            $.ajax({
                type: "post",
                dataType: "json",
                url: "/developer/delete",
                data: {"ids": ids},
                success: function (json) {
                    if (json.code == 200) {
                        layer.msg('删除成功', {icon: 1, time: 1000}, function () {
                            if (typeof callback == 'function') {
                                callback();
                            }
                        });
                    } else {
                        layer.alert(json.msg)
                    }
                }
            })
        }

        //单个删除
        $('.delete').on('click', function () {
            var ids = [];
            var tr = $(this).closest('tr');
            ids.push(tr.data('id'));
            layer.confirm('确定要删除吗？', {btn:['确定', '取消']}, function () {
                batchdel(ids, function () {
                    tr.remove();
                });
            });
        });

    });
</script>
</body>
</html>
