<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>

<body>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">编辑会员信息</div>
                <div class="layui-card-body" pad15>
                    <div class="layui-form" lay-filter="">
                        <div class="layui-form-item">
                            <label class="layui-form-label">会员ID</label>
                            <div class="layui-input-inline">
                                <input type="text" name="id" value="<?= $info['id'] ?>" disabled
                                       class="layui-input user_id">
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>

                        <div class="layui-form-item">
                            <label class="layui-form-label">会员名</label>
                            <div class="layui-input-inline">
                                <input type="text" value="<?= $info['username'] ?>" disabled class="layui-input">
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>

                        <div class="layui-form-item">
                            <label class="layui-form-label">昵称</label>
                            <div class="layui-input-inline">
                                <input type="text" name="nickname" value="<?= $info['nickname'] ?>" class="layui-input">
                            </div>
                        </div>

                        <div class="layui-form-item">
                            <label class="layui-form-label">手机号码</label>
                            <div class="layui-input-inline">
                                <input type="hidden" name="mobile" id="mobile_real" value="<?= $info['mobile'] ?>">
                                <input type="text" value="<?= $info['phone'] ?>" class="layui-input mobile">
                            </div>
                            <div class="layui-form-mid layui-word-aux">
                                <?php if (!empty($info['phone'])) {
                                    echo '<a href="#" id="cat_mobile" style="color: #3366FF">查看</a>';
                                } ?>

                                <a href="#" id="mobile_btn" style="color: #3366FF">修改手机号</a>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">密码</label>
                            <div class="layui-form-mid layui-word-aux">
                                <a href="#" id="edit_pass_a" data-type="edit_pass" style="color: #3366FF">修改密码</a>
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">头像</label>
                            <div class="layui-input-inline" id="icon_pictures" style="width: 100px">
                                <input type="hidden" name="avatar" value="<?= $info['avatar'] ?>">
                                <img class="layui-upload-img" src="<?= $info['avatar'] ?>" id="icon_img-badge"/>
                            </div>
                            <div class="layui-input-inline" style="top: 53px;width: 101px;">
                                <button type="button" class="layui-btn layui-btn-primary" id="icon_btn_badge">
                                    <i class="layui-icon">&#xe67c;</i>重置头像
                                </button>
                            </div>
                            <div class="layui-form-mid layui-word-aux" style="top: 54px">（等比例图片，不要超过100K）</div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <button class="layui-btn" lay-submit lay-filter="user-edit">提交</button>
                                <a class="layui-btn layui-btn-primary" href="/user/index?p=<?= $p ?>">返回</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script type="text/javascript" src="/common/js/plupload-2.1.2/js/plupload.full.min.js"></script>
<script type="text/javascript" src="/common/js/oss.upload.lib.js?t=20190402"></script>
<script>
    layui.extend({
        autocomplete: '/layuiadmin/autocomplete/autocomplete'
    }).use(['form', 'laydate', 'autocomplete'], function () {
        var $ = layui.$
            , form = layui.form
            , laydate = layui.laydate
            , autocomplete = layui.autocomplete
            , layer = layui.layer;

        form.on('submit(user-edit)', function (obj) {
            $.ajax({
                url: '/user/edit',
                type: "POST",
                dataType: "JSON",
                data: obj.field,
                success: function (resp) {
                    if (resp.code == 200) {
                        layer.msg('编辑成功', {icon: 1, time: 1000}, function () {
                            window.location.reload();
                        });
                    } else {
                        layer.msg(resp.msg, {icon: 5, time: 1000});
                    }
                }
            })
        });

        // 修改手机号
        $("#mobile_btn").on('click', function () {
            var id = $('.user_id').val();
            var mobile = $('.mobile').val();
            $.ajax({
                url: '/user/edit_mobile',
                type: 'POST',
                dataType: 'JSON',
                data: {id: id, mobile: mobile},
                success: function (res) {
                    if (res.code == 200) {
                        layer.msg('修改成功', {icon: 1, time: 1000}, function () {
                            window.location.reload();
                        })
                    } else {
                        layer.msg(res.msg, {icon: 5, time: 1000})
                    }
                }
            })
        });

        var active = {
            edit_pass: function () {
                layer.prompt({
                    title: '输入密码，并确认',
                    formType: 1
                }, function (passwd, index) {
                    if (passwd.length < 6 || passwd.length > 18){
                        layer.msg('密码长度应在6-18个字符之间')
                    }else{
                        layer.close(index);
                        layer.prompt({
                            title: '请再次输入密码，并确认',
                            formType: 1
                        },function (passwd1, index) {
                            var id = $('.user_id').val();
                            $.ajax({
                                url: '/user/edit_pass',
                                type: 'POST',
                                dataType: 'JSON',
                                data: {id:id, passwd: passwd, passwd1:passwd1},
                                success: function (res) {
                                    if (res.code == 200) {
                                        layer.msg('修改成功', {icon:1, time: 1000}, function () {
                                            window.location.reload();
                                        })
                                    } else {
                                        layer.msg(res.msg, {icon: 5})
                                    }
                                }
                            })
                        });
                    }
                });
            },
            cate_layout: function () {
                layer.open({
                    title: '页面层',
                    type: 1,
                    shadeClose: true,
                    area: ['700px', '480px'],
                    btn: ['确定', '取消'],
                    content: $("#layuiadmin-form-role"),
                    yes: function (index, layero) {
                        var $cate_name = '', $cate_id = '';
                        $('#layuiadmin-form-role .layui-form-checked').each(function () {
                            var $checked = $('span', this).text(), $id = $(this).prev().prop('name');
                            $cate_name += '<span class="layui-btn layui-btn-primary layui-btn-sm">' + $checked + ' <i class="layui-icon" style="color:red;">&#xe640;</i></span>';
                            $cate_id += $id + ','
                        });
                        $('#game_cate_names').html($cate_name);
                        $('#cate_ids').val($cate_id.substring(0, $cate_id.length - 1))
                        layer.close(index);
                    }
                });
            },

        };

        $('#edit_pass_a').on('click', function () {
            var type = $(this).data('type');
            active[type] ? active[type].call(this) : '';
        });

        // 查看手机号
        $("#cat_mobile").on('click', function () {
            var mobile = $("#mobile_real").val();
            $(".mobile").val(mobile);
        });

        // icon上传 开始
        var icon_callback_img = function (imgurl) {
            $('input[name="avatar"]').val(imgurl);
            $('#icon_img-badge').attr('src', imgurl).show();
        };

        var img_upload = new ossUpload();
        img_upload.init({
            container_id: 'icon_pictures',
            browse_button: 'icon_btn_badge',
            serverUrl: '/oss/get_token',
            width: 100,
            height: 100,
            wh_model: 'eq',
            callback: icon_callback_img,
        });
        // icon上传 结束

    });
</script>
</body>
</html>