<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>
<body>

<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">编辑管理员</div>
                <div class="layui-card-body" pad15>

                    <div class="layui-form" lay-filter="">
                        <div class="layui-form-item">
                            <label class="layui-form-label">角色</label>
                            <div class="layui-input-inline">
                                <select name="group_id" lay-verify="required" lay-verType="tips">
                                    <option value="">请选择角色</option>
                                    <?php foreach ($groups as $group){?>
                                        <option <?php if($group['id'] == ($edit['group_id'] ?? 0)) {echo 'selected';}?> value="<?=$group['id']?>"><?=$group['title']?></option>
                                    <?php }?>
                                </select>
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">用户名</label>
                            <div class="layui-input-inline">
                                <input type="text" name="username" value="<?=$edit['username'] ?? '';?>" lay-verify="required" lay-verType="tips"  autocomplete="off" class="layui-input">
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">昵称</label>
                            <div class="layui-input-inline">
                                <input type="text" name="nickname" value="<?=$edit['nickname'] ?? '';?>" lay-verify="required" lay-verType="tips" autocomplete="off"  class="layui-input">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">手机</label>
                            <div class="layui-input-inline">
                                <input type="text" name="mobile" value="<?=$edit['mobile'] ?? '';?>" lay-verify="phone" lay-verType="tips" autocomplete="off" class="layui-input">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">密码</label>
                            <div class="layui-input-inline">
                                <input type="password" name="password"  autocomplete="off" id="LAY_password" class="layui-input">
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">确认密码</label>
                            <div class="layui-input-inline">
                                <input type="password" name="repwd"  autocomplete="off" class="layui-input">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">QQ</label>
                            <div class="layui-input-inline">
                                <input type="text" name="qq" value="<?=$edit['qq']?>" class="layui-input">
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">是否商务</label>
                            <div class="layui-input-inline">
                                <input type="hidden" name="is_business" value="0">
                                <input type="checkbox" value="1" <?php if($edit['is_business'] == 1){echo 'checked';}?> name="is_business" lay-skin="switch" lay-text="是|否">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">状态</label>
                            <div class="layui-input-inline">
                                <input type="hidden" name="status" value="0">
                                <input type="checkbox" value="1" <?php if($edit['status'] == 1){echo 'checked';}?> name="status" lay-skin="switch" lay-text="正常|锁定">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <input type="hidden" name="id" value="<?=$edit['id'] ?? 0;?>">
                                <button class="layui-btn" lay-submit lay-filter="admin-edit">提交</button>
                                <a class="layui-btn layui-btn-primary" href="/admin/index?p=<?= $p ?>">返回</a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.use('form', function () {
        var $ = layui.$
            , form = layui.form
            , layer = layui.layer;

        /*form.verify({
            nickname: [/^[\S]{2,16}$/, '昵称最少2个字符'],
        })*/

        form.on('submit(admin-edit)', function (obj) {
            $.ajax({
                url: '/admin/edit',
                type: "POST",
                dataType: "JSON",
                data: obj.field,
                success: function (resp) {
                    if (resp.code == 200) {
                        layer.msg('更新成功', {icon: 1, time: 1000}, function () {
                            location.href = '/admin/index';
                        });
                    } else {
                        layer.msg(resp.msg, {icon: 5, time: 1000});
                    }
                }
            })
        })
    });
</script>
</body>
</html>