<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>
<body>
<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-card-body">
            <div style="padding-bottom: 10px;">
                <a class="layui-btn" href="/admin/add">添加</a>
                <a class="layui-btn layui-btn-danger" id="batchdel">删除</a>
            </div>
            <table class="layui-table layui-form">
                <colgroup>
                    <col width="60">
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col width="100">
                    <col width="150">
                </colgroup>
                <thead>
                <tr>
                    <th><input type="checkbox" lay-filter="check-all" lay-skin="primary"></th>
                    <th>ID</th>
                    <th>用户名</th>
                    <th>昵称</th>
                    <th>手机号</th>
                    <th>角色</th>
                    <th>创建时间</th>
                    <th>登录时间</th>
                    <th>登录IP</th>
                    <th>状态</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($list as $user) { ?>
                    <tr data-id="<?= $user['id'] ?>">
                        <td><input type="checkbox" name="ids" lay-skin="primary" value="<?= $user['id'] ?>"></td>
                        <td><?= $user['id'] ?></td>
                        <td><?= $user['username'] ?></td>
                        <td><?= $user['nickname'] ?></td>
                        <td><?= $user['mobile'] ?></td>
                        <td><?= $groups[$user['group_id']]['title'] ?? '' ?></td>
                        <td><?= date('Y-m-d', $user['addtime']); ?></td>
                        <td><?= $user['last_login_time'] > 0 ? date('Y-m-d', $user['last_login_time']) : ''; ?></td>
                        <td><?= long2ip($user['last_login_ip']) ?></td>
                        <td><input type="checkbox" value="1" lay-filter="status"
                                   name="status" <?= ($user['status'] == 1) ? 'checked' : '' ?> lay-skin="switch"
                                   lay-text="正常|锁定"></td>
                        <td>
                            <a class="layui-btn layui-btn-xs" href="/admin/edit?id=<?= $user['id'] ?>&p=<?= $curpage ?>"><i
                                        class="layui-icon layui-icon-edit"></i>编辑</a>
                            <a class="layui-btn layui-btn-danger layui-btn-xs delete"><i
                                        class="layui-icon layui-icon-delete"></i>删除</a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            <?= $page ?>
        </div>
    </div>
</div>

<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.use('form', function () {
        var $ = layui.$
            , form = layui.form;

        //全选
        form.on('checkbox(check-all)', function (data) {
            $('input[name="ids"]').prop("checked", data.elem.checked);
            form.render('checkbox');
        });

        //启用禁用
        form.on('switch(status)', function (data) {
            console.log(data.elem.checked)
            var id = $(this).closest('tr').data('id');
            var status = data.elem.checked ? 1 : 0;
            $.ajax({
                type: "post",
                dataType: "json",
                url: "/admin/toggle",
                data: {id: id, status: status},
                success: function (json) {
                    if (json.code == 200) {
                        layer.msg('操作成功');
                    } else {
                        layer.alert(json.msg);
                    }
                }
            });
        });

        //批量删除
        $('#batchdel').on('click', function () {
            var ids = [];
            $('input[name="ids"]:checked').each(function () {
                ids.push($(this).val())
            });
            if (ids.length <= 0) {
                layer.msg('请先选择用户', {icon:5, time:1000});
                return false;
            }
            layer.confirm('确定要删除吗？', {btn: ['确定', '取消']}, function () {
                batchdel(ids, function () {
                    location.href = location.href;
                });
            });
        });

        function batchdel(ids, callback) {
            $.ajax({
                type: "post",
                dataType: "json",
                url: "/admin/delete",
                data: {"ids": ids},
                success: function (json) {
                    if (json.code == 200) {
                        layer.msg('删除成功', {icon: 1, time: 1000}, function () {
                            if (typeof callback == 'function') {
                                callback();
                            }
                        });
                    } else {
                        layer.alert(json.msg);
                    }
                }
            });
        }

        //单个删除
        $('.delete').on('click', function () {
            var ids = [];
            var tr = $(this).closest('tr');
            ids.push(tr.data('id'));

            layer.confirm('确定要删除吗？', {btn: ['确定', '取消']}, function () {
                batchdel(ids, function () {
                    tr.remove();
                })
            });
        });
    });
</script>
</body>
</html>
