<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>
<body>
<div class="layui-fluid">
    <div class="layui-card">
        <div class="layui-form layui-card-header layuiadmin-card-header-auto layui-row">
            <div class="layui-col-xs2">
                <div class="layui-inline"><a class="layui-btn" href="/coin_expense_daily/index">排行榜</a></div>
            </div>
            <form method="get">
                <div class="layui-col-xs10 text-right">
                    <div class="layui-inline" style="width: 200px">
                        <input type="text" name="order_no" id="order_no" value="<?= $order_no ?>" placeholder="订单号"
                               autocomplete="off"
                               class="layui-input">
                    </div>
                    <div class="layui-inline" style="width: 140px">
                        <input type="hidden" name="user_id" id="user_id" value="<?= $user_id ?>">
                        <input type="text" name="user_name" id="user_name" value="<?= $user_name ?>" placeholder="会员名"
                               autocomplete="off"
                               class="layui-input">
                    </div>
                    <div class="layui-inline text-left" style="width: 140px">
                        <select name="expense_type" id="">
                            <option value="">选择消耗类型</option>
                            <?php foreach ($expenseTypeList as $value) { ?>
                                <option value="<?= $value['id'] ?>" <?= $expense_type == $value['id'] ? 'selected' : '' ?>><?= $value['name'] ?></option>
                            <?php } ?>
                        </select>
                    </div>
                    <div class="layui-inline" style="width: 120px;">
                        <input type="text" name="start_time" id="start_time" value="<?= $start_time ?>"
                               placeholder="开始日期" autocomplete="off" class="layui-input">
                    </div>
                    <span class="layui-inline">至</span>
                    <div class="layui-inline" style="width: 120px;">
                        <input type="text" name="end_time" id="end_time" value="<?= $end_time ?>"
                               placeholder="结束日期" autocomplete="off" class="layui-input">
                    </div>
                    <div class="layui-inline">
                        <button class="layui-btn layuiadmin-btn-list" type="submit">
                            <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <div class="layui-row highlight-block">
            <div class="layui-col-md12">
                交易总金额：<span><?= $total_amount ?></span>
                成功交易：<span><?= $success_amount ?></span>
                失败交易：<span><?= $error_amount ?></span>
            </div>
        </div>
        <div class="layui-card-body">
            <table class="layui-table layui-form" id="table_id">
                <colgroup>
                    <col>
                    <col width="240">
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                </colgroup>
                <thead>
                <tr>
                    <th>编号</th>
                    <th>时间</th>
                    <th>订单号</th>
                    <th>会员名</th>
                    <th>消耗类型</th>
                    <th>转入会员名</th>
                    <th>金额</th>
                    <th>订单状态</th>
                    <th>备注</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($list as $item) { ?>
                    <tr data-id="<?= $item['id'] ?>">
                        <td><?= $item['id'] ?></td>
                        <td><?= $item['addtime'] != 0 ? date('Y-m-d H:i:s', $item['addtime']) : '' ?></td>
                        <td><?= $item['order_no'] > 0 ? $item['order_no'] : '' ?></td>
                        <td><?= $userInfos[$item['user_id']]['username'] ?? '' ?></td>
                        <td><?= $expenseType[$item['expense_type']]['name'] ?? '' ?></td>
                        <td></td>
                        <td><?= $item['amount'] ?></td>
                        <td><?= $item['status'] == 1 ? "交易成功" : "交易失败" ?></td>
                        <td><?= $item['remarks'] ?></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            <?= $page ?>
        </div>
    </div>
</div>

<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.extend({
        autocomplete: '/layuiadmin/autocomplete/autocomplete'
    }).use(['form', 'laydate', 'table', 'autocomplete'], function () {
        var $ = layui.$,
            laydate = layui.laydate,
            table = layui.table,
            form = layui.form,
            autocomplete = layui.autocomplete;

        // 搜索订单号
        $('#order_no').on('keydown', function (event) {
            if (event.keyCode == 8) {
                $('input[name="order_no"]').val('')
            }
        });
        autocomplete.init({
            elem: "#order_no",
            textLength: 2,//触发长度
            delay: 200,//触发延迟
            callback: {
                data: function (val, render) {
                    $.ajax({
                        type: "post",
                        dataType: "json",
                        url: "/coin_expense_log/autocomplete",
                        data: {name: val},
                        success: function (json) {
                            if (json.code == 200) {
                                render(json.data);
                            } else {
                                layer.alert(json.msg);
                            }
                        }
                    });
                },
                selected: function (data) {
                    console.log(data);
                    $('input[name="order_no"]').val(data.value)
                },
                close: function () {
                }
            }
        });

        // 搜索会员名
        $('#user_name').on('keydown', function (event) {
            if (event.keyCode == 8) {
                $('input[name="user_id"]').val('')
            }
        });
        autocomplete.init({
            elem: "#user_name",
            textLength: 2,//触发长度
            delay: 200,//触发延迟
            callback: {
                data: function (val, render) {
                    $.ajax({
                        type: "post",
                        dataType: "json",
                        url: "/user/autocomplete",
                        data: {name: val},
                        success: function (json) {
                            if (json.code == 200) {
                                render(json.data);
                            } else {
                                layer.alert(json.msg);
                            }
                        }
                    });
                },
                selected: function (data) {
                    console.log(data);
                    $('input[name="user_id"]').val(data.value)
                },
                close: function () {
                }
            }
        });

        //开始日期
        var insStart = laydate.render({
            elem: '#start_time'
            , done: function (value, date) {
                //更新结束日期的最小日期
                insEnd.config.min = lay.extend({}, date, {
                    month: date.month - 1
                });

                //自动弹出结束日期的选择器
                insEnd.config.elem[0].focus();
            }
        });

        //结束日期
        var insEnd = laydate.render({
            elem: '#end_time'
            , done: function (value, date) {
                //更新开始日期的最大日期
                insStart.config.max = lay.extend({}, date, {
                    month: date.month - 1
                });
            }
        });
    });
</script>
</body>
</html>
