<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/layuiadmin/layui/css/layui.css" media="all">
    <link rel="stylesheet" href="/layuiadmin/style/admin.css?v=20190515" media="all">
</head>
<body>

<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-header">添加广告位</div>
                <div class="layui-card-body" pad15>

                    <div class="layui-form" lay-filter="">
                        <div class="layui-form-item">
                            <label class="layui-form-label">名称</label>
                            <div class="layui-input-inline">
                                <input type="text" name="title" value="" lay-verify="required" lay-verType="tips"  autocomplete="off" class="layui-input">
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">图标尺寸</label>
                            <div class="layui-input-inline" style="width: 82px">
                                <input type="text" name="icon_width" value="" lay-verify="required" lay-verType="tips" placeholder="宽" autocomplete="off"  class="layui-input">
                            </div>
                            <div class="layui-form-mid">*</div>
                            <div class="layui-input-inline" style="width: 82px">
                                <input type="text" name="icon_height" value="" lay-verify="required" lay-verType="tips" placeholder="高" autocomplete="off"  class="layui-input">
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">图片尺寸</label>
                            <div class="layui-input-inline" style="width: 82px">
                                <input type="text" name="width" value="" lay-verify="required" lay-verType="tips" placeholder="宽" autocomplete="off"  class="layui-input">
                            </div>
                            <div class="layui-form-mid">*</div>
                            <div class="layui-input-inline" style="width: 82px">
                                <input type="text" name="height" value="" lay-verify="required" lay-verType="tips" placeholder="高" autocomplete="off"  class="layui-input">
                            </div>
                            <div class="layui-form-mid layui-word-aux"></div>
                        </div>

                        <div class="layui-form-item">
                            <div class="layui-input-block">
                                <button class="layui-btn" lay-submit lay-filter="adzone-add">提交</button>
                                <a class="layui-btn layui-btn-primary" href="javascript:void(0);" onclick="history.go(-1)">返回</a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<script src="/layuiadmin/layui/layui.js"></script>
<script src="/layuiadmin/common.js"></script>
<script>
    layui.use('form', function () {
        var $ = layui.$
            , form = layui.form
            , layer = layui.layer;

        /*form.verify({
            nickname: [/^[\S]{2,16}$/, '昵称最少2个字符'],
        })*/

        form.on('submit(adzone-add)', function (obj) {
            $.ajax({
                url: '/adzone/add',
                type: "POST",
                dataType: "JSON",
                data: obj.field,
                success: function (resp) {
                    if (resp.code == 200) {
                        layer.msg('添加成功', {icon: 1, time: 1000}, function () {
                            location.href = '/adzone/index';
                        });
                    } else {
                        layer.msg(resp.msg, {icon: 5, time: 1000});
                    }
                }
            })
        });
    });
</script>
</body>
</html>